---
- name: Create Link to Hive Directory
  file:
    src: "{{ hive_root_dir }}"
    dest: "{{ hive.base_path }}/hive"
    owner: "{{ hadoop.user }}"
    group: "{{ hadoop.group }}"
    state: link


- name: Copy Hive Site
  template: src=hive-site.xml dest={{ config.path }} mode=644 owner={{ hadoop.user }} group={{ hadoop.group }}


- name: Copy Hive Env Script
  template: src=hive_env.sh dest=/etc/profile.d/ mode=755


- name: Set Hive Env
  shell: source /etc/profile.d/hive_env.sh
