---
- name: Create Link to Hive Directory
  file:
    src: "{{ hive_root_dir }}"
    dest: "{{ _hive.base_path }}/hive"
    owner: "{{ _hadoop.user }}"
    group: "{{ _hadoop.group }}"
    state: link


- name: Copy Hive Site
  template: src=hive-site.xml dest={{ _config.path }} mode=644 owner={{ _hadoop.user }} group={{ _hadoop.group }}


- name: Copy Hive Env Script
  template: src=hive_env.sh dest=/etc/profile.d/ mode=755


- name: Set Hive Env
  shell: source /etc/profile.d/hive_env.sh

