---
- name: Init HDFS Path
  become_user: "{{ _hadoop.user }}"
  shell: |
    nohup hadoop fs -mkdir -p {{ item }}
  register: init_hdfs_path
  args:
    executable: /bin/bash
    chdir: "{{ _hadoop.base_path }}"
  environment:
    PATH: "{{ hadoop_root_dir }}/bin:/usr/local/bin:{{ ansible_env.PATH }}"
  with_items:
    - "{{ _hdfs_path }}"


- name: Change Authority
  become_user: "{{ _hadoop.user }}"
  shell: |
    nohup hadoop fs -chmod -R 777 {{ item }}
  register: change_authority
  args:
    executable: /bin/bash
    chdir: "{{ _hadoop.base_path }}"
  environment:
    PATH: "{{ hadoop_root_dir }}/bin:/usr/local/bin:{{ ansible_env.PATH }}"
  with_items:
    - "{{ _hdfs_path }}"


- name: Init Hive
  become_user: "{{ _hadoop.user }}"
  shell: |
    nohup schematool -initSchema -dbType {{ _db.type }}
  register: init_hive
  async: 300
  poll: 5
  args:
    executable: /bin/bash
    chdir: "{{ _hadoop.base_path }}"
  environment:
    PATH: "{{ hive_root_dir }}/bin:/usr/local/bin:{{ ansible_env.PATH }}"
    HADOOP_HOME: "{{ hadoop_root_dir }}"
    HADOOP_PREFIX: "{{ hadoop_root_dir }}"

