---
- name: Install PostgreSQL JDBC Driver
  package:
    name: postgresql-jdbc
    state: present
  #vars:
  #  ansible_python_interpreter: "{{ yum_python_version }}"
  # async: 120
  # poll: 5
  # skip_broken: yes


- name: Create Hadoop Path
  file:
    path: "{{ item }}"
    owner: "{{ _hadoop.user }}"
    group: "{{ _hadoop.group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ _config.create_path }}"


- import_tasks: install-hive.yml
  # when: install_hive is defined and install_hive


- import_tasks: config-hive.yml
  # when: config_hive is defined and config_hive


- import_tasks: init-hive.yml
  # when: init_hive is defined and init_hive


