---
- name: Create Hadoop Path
  file: 
    path: "{{ item }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ hive_create_path }}"

- import_tasks: install_hive.yml
  when: install_hive is defined and install_hive

- import_tasks: config_hive.yml
  when: config_hive is defined and config_hive

- import_tasks: init_hive.yml
  when: init_hive is defined and init_hive

- import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'
