---
- name: Check if Apache Hive Tarball File Already Exists
  stat: path={{ hive_file_name }}.{{ hive.bin_type }}
  register: hive_tarball_exists
- debug: msg={{ hive_tarball_exists }}


- name: Check if Apache Hive Installation Directory Already Exists
  stat: path={{ hive.base_path }}/{{ hive_file_name }}
  register: hive_install_dir_exists


- name: Sanity check for existence of {{ hive_file_name }}.{{ hive.bin_type }} file or {{ hive_file_name }} directory
  debug: msg="Both {{ hive_file_name }}.{{ hive.bin_type }} file and {{ hive_file_name }} Directory Already Exists"
  changed_when: hive_tarball_exists.stat.exists == True and hive_install_dir_exists.stat.exists == True


- name: Copy Apache Hive Tarball from local directory, roles/hive/files
  copy: src={{ hive_file_name }}.{{ hive.bin_type }} dest={{ hive.base_path }}/{{ hive_file_name }}.{{ hive.bin_type }} mode=0644 owner={{ hadoop.user }} group={{ hadoop.group }}
  register: local_copy_dss
  when: hadoop.download == false and hive_tarball_exists.stat.exists != True


- name: Unarchive Apache Hive Tarball
  unarchive:
    src: "{{ hive.base_path }}/{{ hive_file_name }}.{{ hive.bin_type }}"
    dest: "{{ hive.base_path }}"
    owner: "{{ hadoop.user }}"
    group: "{{ hadoop.group }}"
    mode: "0755"
    remote_src: yes
  register: unarchive_hive_tarball
  when: hive_install_dir_exists.stat.exists == false


