---
# https://github.com/mcsrainbow/ansible-playbook-cdh5/blob/master/roles/cdh5-hive/tasks/main.yml
- name: Check OS ( Hive )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags:
    - install
    - uninstall


- name: Disable Firewall
  import_tasks: disable-firewall.yml
  tags: install
  when: hive.firewall == true


- name: Install Hive
  import_tasks: install-hive.yml
  tags: install
  when: install_hive is defined and install_hive


- name: Config Hive
  import_tasks: config-hive.yml
  tags: install
  when: config_hive is defined and config_hive


- name: Initialize Hive
  import_tasks: init-hive.yml
  tags: install
  when: init_hive is defined and init_hive


- name: Uninstall Hive
  import_tasks: uninstall.yml
  tags: uninstall


- name: Enable Firewall
  import_tasks: enable-firewall.yml
  tags: uninstall
  when: hive.firewall == true

