---
# https://github.com/mcsrainbow/ansible-playbook-cdh5/blob/master/roles/cdh5-hive/tasks/main.yml
- name: Check OS ( Hive )
  fail: msg="Not a Red Hat based system!"
  when: ( ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky' ) and inventory_hostname in groups['hive']


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: install, uninstall, enable, disable, setup, remove, config, init, uninit


- name: Install Hive
  import_tasks: install-hive.yml
  tags: setup, install
  when: (( hive is defined and hive == true ) or ( hive_all is defined and hive_all == true )) and inventory_hostname not in groups['database']


- name: Config Hive
  import_tasks: config-hive.yml
  tags: config, install
  when: (( hive is defined and hive == true ) or ( hive_all is defined and hive_all == true )) and inventory_hostname not in groups['database']


- name: Setup JDBC
  import_tasks: setup-jdbc.yml
  tags: setup, install
  when: (( jdbc is defined and jdbc == true ) or ( hive_all is defined and hive_all == true )) and inventory_hostname not in groups['database']


- name: Initialize Hive
  import_tasks: init-hive.yml
  tags: init, install
  when: (( hive is defined and hive == true ) or ( hive_all is defined and hive_all == true )) and inventory_hostname in groups['hive']


- name: Uninstall Hive
  import_tasks: uninstall.yml
  tags: delete, remove, uninstall
  when: (( hive is defined and hive == true ) or ( hive_all is defined and hive_all == true )) and inventory_hostname not in groups['database']

