---
- name: Get Network Interface Name from Prefix of IP Addresses
  set_fact:
    netdev0: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', hive.net.ipaddr0 ) | map(attribute='device') | first }}"
    netdev1: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', hive.net.ipaddr1 ) | map(attribute='device') | first }}"


- name: Get IP Address from Network Device Name
  set_fact:
    ipaddr0: "{{ hostvars[inventory_hostname]['ansible_'~netdev0].ipv4.address }}"
    ipaddr1: "{{ hostvars[inventory_hostname]['ansible_'~netdev1].ipv4.address }}"


- name: Define Fact for Hive Version
  set_fact:
    hive_version: "{{ hive.major_version }}.{{ hive.minor_version }}.{{ hive.patch_version }}"
    hive_file_name: "apache-hive-{{ hive.major_version }}.{{ hive.minor_version }}.{{ hive.patch_version }}-bin"
    hive_root_dir: "{{ hive.base_path }}/apache-hive-{{ hive.major_version }}.{{ hive.minor_version }}.{{ hive.patch_version }}-bin"

