---
- name: Remove Hive Configuration, Environment and Binary
  file:
    path: "{{ item }}"
    owner: "{{ _hadoop.user }}"
    group: "{{ _hadoop.group }}"
    state: absent
  with_items:
    - "{{ _config.path }}/hive-site.xml"
    - "{{ _hive.base_path }}/{{ hive_file_name }}.{{ _hive.bin_type }}"
    - "/etc/profile.d/hive_env.sh"


- name: Remove Hive Path
  file:
    path: "{{ item }}"
    owner: "{{ _hadoop.user }}"
    group: "{{ _hadoop.group }}"
    state: absent
    mode: 0755
  with_items:
    - "{{ _config.create_path }}"
    - "{{ _hdfs_path }}"
    - "{{ _hive.base_path }}/hive"
    - "{{ _hive.base_path }}/{{ hive_file_name }}"

