---
ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"


_hadoop:
  user: hadoop
  group: hadoop
  domain: "jtest.pivotal.io"
  hdfs_port: 9000
  base_path: "/home/hadoop"
  download: false
  firewall: false
  download_path: /tmp
  major_version: "3"
  minor_version: "3"
  patch_version: "6"
  bin_type: "tar.gz"
  download_url: "https://dlcdn.apache.org/hadoop/common"
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.19"
    ipaddr1: "192.168.1.19"
    ipaddr2: "192.168.2.19"
  dashboard:
    port: 9870
  dfs:
    namenode_httpport: 9001
    nameservices: "ha-cluster"
  yarn:
    cluster_id: "my-yarn-cluster"
    resmgr_port: 8040
    resmgr_scheduler_port: 8030
    resmgr_webapp_port: 8088
    resmgr_tracker_port: 8025
    resmgr_admin_port: 8141
  vms:
    rk9: [ "rk9-freeipa", "rk9-node01", "rk9-node02", "rk9-node03", "rk9-node04", "rk9-node05", "rk9-node06", "rk9-node07" ]
    ubt24: [ "rk9-freeipa", "ubt24-node01", "ubt24-node02", "ubt24-node03", "ubt24-node04", "ubt24-node05", "ubt24-node06", "ubt24-node07" ]
  debug_opt: ""  # --debug


_zookeeper:
  user: zookeeper
  group: zookeeper
  major_version: 3
  minor_version: 9
  patch_version: 3
  base_path: /usr/local
  download: false
  download_url: http://apache.rediris.es/zookeeper
  download_path: /tmp
  config:
    port: 2181
    log_path: /usr/local/apache-zookeeper/log
    data_dir: /usr/local/apache-zookeeper/data
    tick_time: 2000
    init_limit: 5
    sync_limit: 2
  use_internal_zookeeper: false
  # log_path: /var/log/zookeeper
  # data_dir: /var/lib/zookeeper
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.19"
    ipaddr1: "192.168.1.19"
    ipaddr2: "192.168.2.19"


_hive:
  user: "{{ _hadoop.user }}"
  group: "{{ _hadoop.group }}"
  download: false
  firewall: false
  major_version: 4
  minor_version: 0
  patch_version: 1
  bin_type: tar.gz
  download_url: "https://dlcdn.apache.org/hive"
  base_path: "{{ _hadoop.base_path }}"
  default_path: "/user/hive"
  tmp_path: "{{ _hadoop.base_path }}/hive/tmp"
  server_port: 10000
  hwi_port: 9999
  metastore_port: 9083
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.19"
    ipaddr1: "192.168.1.19"
    ipaddr2: "192.168.2.19"
  jdbc:
    pgsql:
      download_url: "https://jdbc.postgresql.org/download"
      major_version: 42
      minor_version: 7
      patch_version: 5
      bin_type: jar


_spark:
  worker:
    core: 6
    memory: "6G"
    default_core: 4
  download: false
  firewall: false
  user: "{{ _hadoop.user }}"
  group: "{{ _hadoop.group }}"
  major_version: 3
  minor_version: 5
  patch_version: 4
  bin_type: tgz
  download_url: "https://archive.apache.org/dist/spark"
  base_path: "{{ _hadoop.base_path }}"
  master_work_port: 7077
  worker_work_port: 7078
  master_ui_port: 8080
  worker_ui_port: 8081
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.19"
    ipaddr1: "192.168.1.19"
    ipaddr2: "192.168.2.19"


_hbase:
  user: "{{ _hadoop.user }}"
  group: "{{ _hadoop.group }}"
  base_path: "{{ _hadoop.base_path }}"
  download: false
  firewall: false
  major_version: 2
  minor_version: 6
  patch_version: 1
  bin_type: tar.gz
  download_url: "https://archive.apache.org/dist/hbase"
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.19"
    ipaddr1: "192.168.1.19"
    ipaddr2: "192.168.2.19"


_ganglia:
  user: "ganglia"
  group: "ganglia"
  base_path: "/var/www"
  firewall: false
  web:
    major_version: 3
    minor_version: 7
    patch_version: 2
    bin_type: tar.gz
    download: false
    firewall: false
    apache_user: apache
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.19"
    ipaddr1: "192.168.1.19"
    ipaddr2: "192.168.2.19"
  cluster_name: "Hadoop-ZKcluster"
  site_name: "FFHaddop"
  mtu: 9216 # IPv4 maximum transmission unit, 9216 is the maximum for Intel/Cisco hardware
  upgrade_kernel: no

  # To enable Postfix SMTP through Mandrill (@mandrillapp), set the following variables:
  # notify_email: notifications@example.com
  # postfix_domain: example.com
  # mandrill_username: your_username
  # mandrill_api_key: your_api_key
  # Upgrade kernel to 3.13, much improved epoll performance


_postgres:
  firewall: false
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.19"
    ipaddr1: "192.168.1.19"
    ipaddr2: "192.168.2.19"


_impala:
  user: "hadoop"
  group: "hadoop"
  base_path: "{{ _hadoop.base_path }}"
  major_version: 4
  minor_version: 4
  patch_version: 1
  bin_type: tar.gz
  download: false
  firewall: false
  download_url: "https://archive.apache.org/dist/impala"
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.19"
    ipaddr1: "192.168.1.19"
    ipaddr2: "192.168.2.19"


_cassandra:
  user: "hadoop"
  group: "hadoop"
  base_path: "{{ _hadoop.base_path }}"
  major_version: 4
  minor_version: 1
  patch_version: 8
  bin_type: tar.gz
  download: false
  firewall: false
  download_url: "https://archive.apache.org/dist/cassandra"
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.19"
    ipaddr1: "192.168.1.19"
    ipaddr2: "192.168.2.19"


_kudu:
  user: "hadoop"
  group: "hadoop"
  base_path: "{{ _hadoop.base_path }}"
  major_version: 1
  minor_version: 9
  patch_version: 0
  bin_type: tar.gz
  download: false
  firewall: false
  download_url: "https://archive.apache.org/dist/kudu"
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.19"
    ipaddr1: "192.168.1.19"
    ipaddr2: "192.168.2.19"


_jdk:
  oss:
    install: true
    jvm_home: "/usr/lib/jvm"
    major_version: 1
    minor_version: 8
    patch_version: 0
    # 1.8.0
    # 11.0.4
    # 17.0.2
  oracle:
    install: false
    jvm_home: "/usr/lib/jvm"
    major_version: 13
    minor_version: 0
    patch_version: 2
    download: false


vmware:
  esxi_hostname: "192.168.0.231"
  esxi_username: "root"
  esxi_password: "Changeme34#$"


kvm:
  hostname: "192.168.0.101"
  username: "root"
  password: "changeme"

