ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"

hadoop:
  user: hadoop
  group: hadoop
  domain: "jtest.pivotal.io"
  hdfs_port: 9000
  base_path: "/home/hadoop"
  download: false
  firewall: false
  download_path: /tmp
  major_version: "3"
  minor_version: "3"
  patch_version: "6"
  bin_type: "tar.gz"
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.7"
    ipaddr1: "192.168.1.7"
    ipaddr2: "192.168.2.7"
  dfs:
    namenode_httpport: 9001
    nameservices: ha-cluster
  yarn:
    resmgr_port: 8040
    resmgr_scheduler_port: 8030
    resmgr_webapp_port: 8088
    resmgr_tracker_port: 8025
    resmgr_admin_port: 8141


hive:
  user: "{{ hadoop.user }}"
  group: "{{ hadoop.group }}"
  download: false
  firewall: false
  major_version: 3
  minor_version: 1
  patch_version: 3
  bin_type: tar.gz
  base_path: "{{ hadoop.base_path }}"
  default_path: "/user/hive"
  tmp_path: "{{ hadoop.base_path }}/hive/tmp"
  server_port: 10000
  hwi_port: 9999
  metastore_port: 9083
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.7"
    ipaddr1: "192.168.1.7"
    ipaddr2: "192.168.2.7"


spark:
  worker:
    core: 6
    memory: "6G"
    default_core: 4
  download: false
  firewall: false
  user: "{{ hadoop.user }}"
  group: "{{ hadoop.group }}"
  major_version: 3
  minor_version: 5
  patch_version: 2
  bin_type: tgz
  base_path: "{{ hadoop.base_path }}"
  master_work_port: 7077
  worker_work_port: 7078
  master_ui_port: 8080
  worker_ui_port: 8081
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.7"
    ipaddr1: "192.168.1.7"
    ipaddr2: "192.168.2.7"


hbase:
  user: "{{ hadoop.user }}"
  group: "{{ hadoop.group }}"
  download: false
  firewall: false
  major_version: 2
  minor_version: 6
  patch_version: 0
  bin_type: tar.gz
  base_path: "{{ hadoop.base_path }}"
  default_path: "/opt/hbase"
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.7"
    ipaddr1: "192.168.1.7"
    ipaddr2: "192.168.2.7"


postgres:
  firewall: false
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.7"
    ipaddr1: "192.168.1.7"
    ipaddr2: "192.168.2.7"


jdk:
  oss:
    install: true
    jvm_home: "/usr/lib/jvm"
    major_version: 1
    minor_version: 8
    patch_version: 0
    pkgs:
      - "java-1.8.0-openjdk"
      - "java-1.8.0-openjdk-devel"
  oracle:
    install: false
    jvm_home: "/usr/lib/jvm"
    major_version: 1
    minor_version: 8
    patch_version: 0
    pkgs:
      - "java-1.8.0-openjdk"
      - "java-1.8.0-openjdk-devel"


vmware:
  esxi_hostname: "192.168.0.231"
  esxi_username: "root"
  esxi_password: "Changeme34#$"

