ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"

hadoop:
  user: jomoon
  group: jomoon
  domain: "jtest.pivotal.io"
#  major_version: "13"
#  minor_version: "0"
#  patch_version: "3"
#  build_version: ""
#  base_path: "/home/jomoon"
#  bin_type: "tar.gz"
  download: false
  net:
    type: "virtual"                # Or Physical
    gateway: "192.168.0.1"
    ipaddr0: "192.168.0.7"
    ipaddr1: "192.168.1.7"
    ipaddr2: "192.168.2.7"

#postgres:
#  net:
#    type: "virtual"                # Or Physical
#    gateway: "192.168.0.1"
#    ipaddr0: "192.168.0.7"
#    ipaddr1: "192.168.1.7"
#    ipaddr2: "192.168.2.7"

