---
- name: Check OS ( Zookeeper )
  fail: msg="Not a Red Hat based system!"
  when: ( ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky' ) and inventory_hostname in groups['zk_servers']


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: install, uninstall, setup, remove
  when: inventory_hostname in groups['zk_servers']


- name: Install ZooKeeper
  import_tasks: install.yml
  tags: setup, install
  when: inventory_hostname in groups['zk_servers']


- name: Uninstall Zookeeper
  import_tasks: uninstall.yml
  tags: remove, uninstall
  when: inventory_hostname in groups['zk_servers']

