---
- name: Check OS ( Zookeeper )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS'  ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: setup, remove, install, uninstall


- name: Install ZooKeeper
  import_tasks: install.yml
  tags: setup, install
  when: inventory_hostname not in groups['database']


- name: Uninstall Zookeeper
  import_tasks: uninstall.yml
  tags: remove, uninstall
  when: inventory_hostname not in groups['database']

