---
# For now fail if it's not a Red Hat based system
- name: Check OS ( Zookeeper )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS'  ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags:
    - install
    - uninstall


- name: Install ZooKeeper
  import_tasks: install.yml
  tags: install
  when: inventory_hostname in groups['master'] or inventory_hostname in groups['standby'] or inventory_hostname in groups['workers']


- name: Uninstall Zookeeper
  import_tasks: uninstall.yml
  tags: uninstall
  when: inventory_hostname in groups['master'] or inventory_hostname in groups['standby'] or inventory_hostname in groups['workers']

