---
- name: Get Network Interface Name from Prefix of IP Addresses
  set_fact:
    netdev0: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', zookeeper.net.ipaddr0 ) | map(attribute='device') | first }}"
    netdev1: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', zookeeper.net.ipaddr1 ) | map(attribute='device') | first }}"
    netdev2: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', zookeeper.net.ipaddr2 ) | map(attribute='device') | first }}"


- name: Get IP Address from Network Device Name
  set_fact:
    ipaddr0: "{{ hostvars[inventory_hostname]['ansible_'~netdev0].ipv4.address }}"
    ipaddr1: "{{ hostvars[inventory_hostname]['ansible_'~netdev1].ipv4.address }}"
    ipaddr2: "{{ hostvars[inventory_hostname]['ansible_'~netdev1].ipv4.address }}"


- name: Define Fact for Kafka/Zookeeper Version
  set_fact:
    hadoop_version: "{{ hadoop.major_version }}.{{ hadoop.minor_version }}.{{ hadoop.patch_version }}"
    zookeeper_version: "{{ zookeeper.major_version }}.{{ zookeeper.minor_version }}.{{ zookeeper.patch_version }}"
    # scala_version: "{{ kafka.scala.major_version}}.{{ kafka.scala.minor_version }}"


- name: Set Kafka/Zookeeper Package Name and Application Path
  set_fact:
    hadoop_file_name: "hadoop-{{ hadoop_version }}"
    hadoop_package_name: "hadoop-{{ hadoop_version }}.tar.gz"
    hadoop_application_path: "{{ hadoop.base_path }}/hadoop-{{ hadoop_version }}"
    zookeeper_file_name: "apache-zookeeper-{{ zookeeper_version }}-bin"
    zk_package_name: apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz
    zk_application_path: "{{ zookeeper.base_path }}/apache-zookeeper-{{ zookeeper_version }}-bin"


- name: Set Default Network Device and Address
  set_fact:
    _netdev: "{{ netdev0 }}"
    _ipaddr: "{{ ipaddr0 }}"

