---
#
- set_fact:
    zk_package_name: apache-zookeeper-{{ zookeeper.version }}-bin.tar.gz
    zk_application_path: "{{ zookeeper.installation_path }}/apache-zookeeper-{{ zookeeper.version }}-bin"

#
- name: Stop zookeeper service
  shell: "systemctl stop zookeeper"

#
- name: Delete files of config files and binary
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/systemd/system/zookeeper.service"
    - "{{ zookeeper.configuration.data_dir }}/myid"
    - "{{ zk_application_path }}/conf/zoo.cfg"
    - "{{ package_download_path }}/{{ zk_package_name }}"

#
- name: Delete files of Directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ zookeeper.configuration.data_dir }}"
    - "{{ zookeeper.configuration.log_path }}"
    - "{{ zookeeper.installation_path }}/apache-zookeeper"
    - "{{ zookeeper.installation_path }}/apache-zookeeper-{{ zookeeper.version }}-bin"

#
- name: Reload systemd daemon
  shell: "systemctl daemon-reload"

#
- name: Delete Zookeeper User
  user: name=zookeeper state=absent

#
- name: Delete Zookeeper Group
  group: name=zookeeper state=absent

