---
- name: Check if Apache Hadoop Tarball File Already Exists
  stat: path={{ hadoop_file_name }}.{{ _hadoop.bin_type }}
  register: check_hadoop_tarball
- debug: msg={{ check_hadoop_tarball }}


- name: Check if Apache Hadoop Installation Directory Already Exists
  stat: path={{ _hadoop.base_path }}/{{ hadoop_file_name }}
  register: check_hadoop_install_dir


- name: Sanity check for existence of {{ hadoop_file_name }}.{{ _hadoop.bin_type }} file or {{ hadoop_file_name }} directory
  debug: msg="Both {{ hadoop_file_name }}.{{ _hadoop.bin_type }} file and {{ hadoop_file_name }} Directory Already Exists"
  changed_when: check_hadoop_tarball.stat.exists == True and check_hadoop_install_dir.stat.exists == True


- name: Download Hadoop Software Binaries
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  with_items:
    - { url: "{{ _hadoop.download_url }}/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz",
        dest: "{{ _hadoop.base_path }}/hadoop-{{ hadoop_version }}.tar.gz" }
  when: _hadoop.download == true and check_hadoop_tarball.stat.exists != True


- name: Copy Apache Hadoop Tarball from Local Directory, roles/hadoop/files
  copy: src={{ hadoop_file_name }}.{{ _hadoop.bin_type }} dest={{ _hadoop.base_path }}/{{ hadoop_file_name }}.{{ _hadoop.bin_type }} mode=0644 owner={{ _hadoop.user }} group={{ _hadoop.group }}
  register: local_copy_dss
  when: _hadoop.download == false and check_hadoop_tarball.stat.exists != True


- name: Unarchive Apache Hadoop Tarball
  unarchive:
    src: "{{ _hadoop.base_path }}/{{ hadoop_file_name }}.{{ _hadoop.bin_type }}"
    dest: "{{ _hadoop.base_path }}/"
    owner: "{{ _hadoop.user }}"
    group: "{{ _hadoop.group }}"
    mode: "0755"
    remote_src: yes
  register: unarchive_hadoop_tarball
  when: check_hadoop_install_dir.stat.exists == false


- name: Create Hadoop Path
  file:
    path: "{{ item }}"
    owner: "{{ _hadoop.user }}"
    group: "{{ _hadoop.group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ create_path }}"

