---
#- name: Copy Metadata to Standby master
#  become_user: "{{ _hadoop.user }}"
#  synchronize:
#    src:  "{{ item }}"
#    dest: "{{ item }}"
#    rsync_opts:
#      - "-e ssh"    # "-e ssh -i ~/.ssh/id_rsa.pub"
#    ssh_args:
#      - "-p changeme -o StrictHostKeyChecking=no"
#  delegate_to: "{{ hostvars[groups['standby'][0]]['ansible_hostname'] }}"
#  with_items:
#    - "{{ _hadoop.base_path }}/dfs/data"


- name: Copy Metadata to Standby master
  become_user: "{{ _hadoop.user }}"
  shell: |
    rsync -a --rsh='/usr/bin/sshpass -p changeme ssh -o StrictHostKeyChecking=no' {{ item }} {{ inventory_hostname }}:{{ item }}
  delegate_to: "{{ hostvars[groups['standby'][0]]['ansible_hostname'] }}"
  with_items:
    - "{{ _hadoop.base_path }}/dfs/data"

