---
- name: Start Data nodes
  become_user: "{{ _hadoop.user }}"
  shell: |
    nohup hdfs --daemon start datanode
  register: start_datanode
  args:
    executable: /bin/bash
    chdir: "{{ _hadoop.base_path }}"
  environment:
    PATH: "{{ hadoop_root_dir }}/bin:/usr/local/bin:{{ ansible_env.PATH }}"

