---
- name: Format The Zookeeper Failover Controller In Activie Namenode
  become_user: "{{ _hadoop.user }}"
  shell: |
    hdfs zkfc -formatZK -force
  register: format_zk_failover
  args:
    executable: /bin/bash
    chdir: "{{ _hadoop.base_path }}"
  environment:
    PATH: "{{ hadoop_root_dir }}/bin:/usr/local/bin:{{ ansible_env.PATH }}"

