---
- name: Start the ZKFC in Active or Standby Namenode
  become_user: "{{ _hadoop.user }}"
  shell: |
    nohup hdfs --daemon start zkfc
  register: format_zk_failover
  args:
    executable: /bin/bash
    chdir: "{{ _hadoop.base_path }}"
  environment:
    PATH: "{{ hadoop_root_dir }}/bin:/usr/local/bin:{{ ansible_env.PATH }}"

