---
- name: Start YARN
  become_user: "{{ _hadoop.user }}"
  shell: |
    nohup start-yarn.sh
  register: start_yarn
  args:
    executable: /bin/bash
    chdir: "{{ _hadoop.base_path }}"
  environment:
    PATH: "{{ hadoop_root_dir }}/sbin:/usr/local/bin:{{ ansible_env.PATH }}"

