---
- name: Start YARN Resource Manager
  become_user: "{{ _hadoop.user }}"
  shell: |
    yarn-daemon.sh start resourcemanager
  register: start_yarn_rm
  args:
    executable: /bin/bash
    chdir: "{{ _hadoop.base_path }}"
  environment:
    PATH: "{{ hadoop_root_dir }}/sbin:/usr/local/bin:{{ ansible_env.PATH }}"

# the ResourceManager service on DataNodes are usually not started at this time
# and needs to be started manually

- name: Print the URL of HBase Web UI
  debug:
    msg: "{{ item }}"
  with_items:
    - "Hadoop Master Namenode Web UI with http://{{ hostvars[groups['master'][0]][_netdev]['ipv4']['address'] }}:50070"
    - "Hadoop Standby Namenode Web UI with http://{{ hostvars[groups['standby'][0]][_netdev]['ipv4']['address'] }}:50070"
    - "Master YARN Resource Manager Web UI with http://{{ hostvars[groups['master'][0]][_netdev]['ipv4']['address'] }}:8480"
    - "Standby YARN Resource Manager Web UI with http://{{ hostvars[groups['standby'][0]][_netdev]['ipv4']['address'] }}:8480"
    - "MapReduce JobHistory Server Web UI with http://{{ hostvars[groups['master'][0]][_netdev]['ipv4']['address'] }}:19888"
  when: inventory_hostname in groups['master']
  # 8480 Journal Node

