---
- name: Stop the ZKFC in Active or Standby Namenode
  become_user: "{{ _hadoop.user }}"
  shell: |
    nohup hadoop-daemon.sh stop zkfc
  register: stop_master_zkfs
  ignore_errors: true
  args:
    executable: /bin/bash
    chdir: "{{ _hadoop.base_path }}"
  environment:
    PATH: "{{ hadoop_root_dir }}/sbin:/usr/local/bin:{{ ansible_env.PATH }}"
  when: inventory_hostname in groups['master']


- name: Stop the ZKFC in Active or Standby Namenode
  become_user: "{{ _hadoop.user }}"
  shell: |
    nohup stop-all.sh
  register: stop_standby_zkfs
  ignore_errors: true
  args:
    executable: /bin/bash
    chdir: "{{ _hadoop.base_path }}"
  environment:
    PATH: "{{ hadoop_root_dir }}/sbin:/usr/local/bin:{{ ansible_env.PATH }}"
  when: inventory_hostname in groups['master']


#- name: Kill Processes Hold On User Directory
#  become_user: root
#  shell: |
#    {{ item }}{{ _hadoop.user }}
#  register: kill_user_processes
#  ignore_errors: true
#  # until: kill_user_processes is succeeded
#  # retries: 3
#  with_items:
#    - "nohup pkill -U "
#    - "nohup fuser -k /home/"
#  args:
#    executable: /bin/bash
#    chdir: "{{ _hadoop.base_path }}"
#  environment:
#    PATH: "{{ hadoop_root_dir }}/bin:/usr/local/bin:{{ ansible_env.PATH }}"

