---
- name: Check Public Key
  shell: "chown -R {{ user }}.{{ group }} /home/{{ user }}"
  ignore_errors: true

- name: Check Public Key
  shell: "ls /home/{{ user }}/.ssh|grep '.pub' |wc -l"
  register: key_exist
  ignore_errors: true

- name: Generate Public key
  user:
    name: "{{ user }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  when: "key_exist.stdout == '0' and generate_key"

