---
- name: Check OS ( Hadoop )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS'  ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations for Linux Distribution
  import_tasks: set-facts.yml
  tags: setup, install, uninstall, deploy, destroy, enable, disable, create, delete, add, remove, fetch, disfetch, config, format, bootstrap, start, stop


###########################################################################################################################################################
# Hadoop Installation
###########################################################################################################################################################
#
- name: Disable Firewall
  import_tasks: 01-disable-firewall.yml
  tags: disable, install
  when: (( firewall is defined and firewall == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname not in groups['database']


- name: Install User on All Nodes
  import_tasks: 02-create-public-ssh-key.yml
  tags: create, add, install
  when: (( user is defined and user == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname not in groups['database']


- name: Fetch Public Key on All Nodes
  import_tasks: 03-fetch-public-key.yml
  tags: fetch, install
  when: (( key is defined and key == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname not in groups['database']


- name: Authorize User with Public Key on All Nodes
  import_tasks: 04-add-public-key.yml
  tags: add, install
  when: (( key is defined and key == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname not in groups['database']


- name: Deploy Hadoop
  import_tasks: 05-install-hadoop.yml
  tags: setup, deploy, install
  when: (( hadoop is defined and hadoop == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname not in groups['database']


- name: Config Hadoop
  import_tasks: 06-config-hadoop.yml
  tags: config, install
  when: (( hadoop is defined and hadoop == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname not in groups['database']


- name: Start Journalnode
  import_tasks: 07-start-journalnode.yml
  tags: start, install
  when: (( journal is defined and journal == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname not in groups['database']


- name: Format Namenode on Master
  import_tasks: 08-format-namenode.yml
  tags: format, install
  when: (( master is defined and master == true ) or ( hadoop_all is defined and hadoop_all == true ))  and inventory_hostname in groups['master']


- name: Start Namenode on Master
  import_tasks: 09-start-namenode.yml
  tags: start, install
  when: (( master is defined and master == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname in groups['master']


- name: Copy Metadata from Master to Standby Master
  import_tasks: 10-copy-metadata.yml
  tags: copy, install
  when: (( metadata is defined and metadata == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname in groups['master']


- name: Bootstrap Namenode on Standby Master
  import_tasks: 11-bootstrap-standby.yml
  tags: bootstrap, install
  when: (( standby is defined and standby == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname in groups['standby']


- name: Start Namenode on Standby Master
  import_tasks: 09-start-namenode.yml
  tags: start, install
  when: (( standby is defined and standby == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname in groups['standby']


- name: Start Datanodes on Worker Nodes
  import_tasks: 12-start-datanode.yml
  tags: start, install
  when: (( datanode is defined and datanode == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname in groups['workers']


- name: Format ZKFC on Master Node
  import_tasks: 13-format-zkfc.yml
  tags: format, install
  when: (( zkfc is defined and zkfc == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname in groups['master']


- name: Start ZKFC on Master Node
  import_tasks: 14-start-zkfc.yml
  tags: start, install
  when: (( zkfc is defined and zkfc == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname in groups['master']


- name: Start ZKFC on Standby Master Node
  import_tasks: 14-start-zkfc.yml
  tags: start, install
  when: (( zkfc is defined and zkfc == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname in groups['standby']


- name: Start YARN on Standby Master Node
  import_tasks: 15-start-yarn.yml
  tags: start, install
  when: (( yarn is defined and yarn == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname in groups['standby']


- name: Start YARN Resource Manager on Worker Nodes
  import_tasks: 16-start-yarn-resource-manager.yml
  tags: start, install
  when: (( yrm is defined and yrm == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname in groups['workers']


###########################################################################################################################################################
# Hadoop Uninstallation
###########################################################################################################################################################
#
- name: Stop Hadoop
  import_tasks: 41-stop-hadoop.yml
  tags: stop, uninstall
  when: (( hadoop is defined and hadoop == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname not in groups['database']


- name: Remove Hadoop Config
  import_tasks: 42-remove-hadoop-config.yml
  tags: remove, uninstall
  when: (( hadoop is defined and hadoop == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname not in groups['database']


- name: Remove Public Key
  import_tasks: 43-remove-public-key.yml
  tags: remove, uninstall
  when: (( key is defined and key == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname not in groups['database']


- name: Remove Public Key
  import_tasks: 44-uninstall-fetch-public-key.yml
  tags: remove, uninstall
  when: (( key is defined and key == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname not in groups['database']


- name: Remove User on All Nodes
  import_tasks: 45-remove-user.yml
  tags: remove, uninstall
  when: (( user is defined and user == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname not in groups['database']


- name: Enable Firewalld
  import_tasks: 46-enable-firewall.yml
  tags: enable, uninstall
  when: (( firewall is defined and firewall == true ) or ( hadoop_all is defined and hadoop_all == true )) and inventory_hostname not in groups['database']


- name: Start Hadoop
  import_tasks: ext/start-hadoop.yml
  tags: start
  when: ( hdfs is defined and hdfs == true ) and inventory_hostname not in groups['database']


- name: Stop Hadoop
  import_tasks: ext/stop-hadoop.yml
  tags: stop
  when: ( hdfs is defined and hdfs == true ) and inventory_hostname not in groups['database']

