---
- name: Stop the ZKFC in Active or Standby Namenode
  shell: "su {{ hadoop.user }} -c 'hadoop-daemon.sh stop zkfc'"
  when: inventory_hostname in groups['master']


- name: Stop the ZKFC in Active or Standby Namenode
  shell: "su {{ hadoop.user }} -c 'stop-all.sh'"
  when: inventory_hostname in groups['master']


- name: Kill Processes Hold On User Directory
  shell: |
    su {{ hadoop.user }} -c "nohup pkill -U {{ hadoop.user }}"
    sleep 10


- name: Remove Haddop Directories for Configuration, Log, Data and Journal
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ config.path }}"
  - "{{ config.tmp }}"
  - "{{ config.dfs_name }}"
  - "{{ config.dfs_data }}"
  - "{{ config.log_path }}"
  - "{{ config.journalnode_path }}"
  - "{{ hadoop.base_path }}/hadoop"
  - "{{ hadoop.base_path }}/hadoop-{{ hadoop_version }}"
  - "/etc/profile.d/hadoop_env.sh"

