---
#- name: Delete Public Key
#  file:
#    path: "{{ hadoop.base_path }}/.ssh/id_rsa"
#    state: absent


- name: Kill Processes Hold on User Directory
  become: true
  shell: |
    nohup pkill -U {{ hadoop.user }}
    sleep 10
   # nohup fuser -k {{ hadoop.base_path }}
