- name: Stop the ZKFC in Active or Standby Namenode
  shell: "su {{ user }} -c 'hadoop-daemon.sh stop zkfc'"
  when: inventory_hostname in groups['master']


- name: Stop the ZKFC in Active or Standby Namenode
  shell: "su {{ user }} -c 'stop-all.sh'"
  when: inventory_hostname in groups['master']


- name: Stop Journalnode
  shell: su {{ user }} -c "hdfs --daemon stop journalnode"


- name: Kill Processes Hold On User Directory
  shell: |
    su {{ user }} -c "nohup pkill -U {{ user }}"
    sleep 10


- name: Remove Haddop directories for configure, log, data and journal
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ hadoop_config_path }}"
  - "{{ hadoop_tmp }}"
  - "{{ hadoop_dfs_name }}"
  - "{{ hadoop_dfs_data }}"
  - "{{ hadoop_log_path }}"
  - "{{ hadoop_journalnode_path }}"

