---
- name: Stop the ZKFC in Active or Standby Namenode
  shell: "su {{ hadoop.user }} -c 'hadoop-daemon.sh stop zkfc'"
  when: inventory_hostname in groups['master']


- name: Stop the ZKFC in Active or Standby Namenode
  shell: "su {{ hadoop.user }} -c 'stop-all.sh'"
  when: inventory_hostname in groups['master']


#- name: Stop Journalnode
#  shell: su {{ hadoop.user }} -c "hdfs --daemon stop journalnode"


- name: Kill Processes Hold On User Directory
  shell: |
    su {{ hadoop.user }} -c "nohup pkill -U {{ hadoop.user }}"
    sleep 10


- name: Remove Haddop directories for configure, log, data and journal
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ config.path }}"
  - "{{ config.tmp }}"
  - "{{ config.dfs_name }}"
  - "{{ config.dfs_data }}"
  - "{{ config.log_path }}"
  - "{{ config.journalnode_path }}"
  - "{{ hadoop.base_path }}/hadoop-{{ hadoop_version }}"

