---
- name: Uninstall OpenJDK Package
  package: name={{ item }} state=absent
  with_items:
    - "{{ jdk.oss.pkgs }}"


- name: Comment $JAVA_HOME Variable
  replace:
    path: /etc/profile.d/java_home.sh
    regexp: "^export "
    replace: "#export "


- name: Uncomment Previous Variables for JAVA_HOME
  replace:
    path: /etc/profile.d/java_home.sh
    regexp: "^# "
    replace: ""


- name: Set Java Home Script
  shell: source /etc/profile.d/java_home.sh

