---
hadoop_version: "{{ hadoop.major_version }}.{{ hadoop.minor_version }}.{{ hadoop.patch_version }}"

netinfo:
  ipaddr:
    master: "{{ hostvars[groups['master'][0]]['ansible_'~ netdev0]['ipv4']['address'] }}"
    standby: "{{ hostvars[groups['standby'][0]]['ansible_'~ netdev0]['ipv4']['address'] }}"
  hostname:
    master: "{{ hostvars[groups['master'][0]].ansible_hostname }}"
    standby: "{{ hostvars[groups['standby'][0]].ansible_hostname }}"

config:
  path: "{{ hadoop.base_path }}/hadoop-{{ hadoop_version }}/etc/hadoop"
  tmp: "{{ hadoop.base_path }}/tmp"
  dfs_name: "{{ hadoop.base_path }}/dfs/name"
  dfs_data: "{{ hadoop.base_path }}/dfs/data"
  log_path: "{{ hadoop.base_path }}/hadoop_logs"
  journalnode_path: "{{ hadoop.base_path }}/journalnode/data"


create_path:
  - "{{ config.tmp }}"
  - "{{ config.dfs_name }}"
  - "{{ config.dfs_data }}"
  - "{{ config.log_path }}"
  - "{{ config.journalnode_path }}"

list:
  zkservers: "{{ groups['all'] | map('extract', hostvars, ['ansible_fqdn']) | map('regex_replace', '$', ':2181') | join(',') }}"
  qjournal: "{{ groups['all'] | map('extract', hostvars, ['ansible_hostname']) | map('regex_replace', '$', '.jtest.pivotal.io:8485') | join(';') }}"


core_site_properties:
  - {
      "name":"fs.defaultFS",
      "value":"hdfs://{{ netinfo.ipaddr.master }}:{{ hadoop.hdfs_port }}"
  }
  - {
      "name":"hadoop.tmp.dir",
      "value":"file:{{ config.tmp }}"
  }
  - {
    "name":"io.file.buffer.size",
    "value":"131072"
  }
  - {
      "name":"ha.zookeeper.quorum",
      "value":"{{ list.zkservers }}"
  }
  - {
    "name":"ha.zookeeper.session-timeout.ms",
    "value":"10000"
  }
  - {
    "name":"hadoop.proxyuser.gpadmin.hosts",
    "value":"*"
  }
  - {
    "name":"hadoop.proxyuser.gpadmin.groups",
    "value":"*"
  }

dfs_namenode_httpport: 9001
hdfs_site_properties:
  - {
      "name":"dfs.namenode.name.dir",
      "value":"file:{{ config.dfs_name }}"
  }
  - {
      "name":"dfs.namenode.data.dir",
      "value":"file:{{ config.dfs_data }}"
  }
  - {
      "name":"dfs.replication",
      "value":"{{ groups['workers']|length }}"
  }
  - {
      "name":"dfs.webhdfs.enabled",
      "value":"true"
  }
  - {
      "name":"dfs.nameservices",
      "value":"ha-cluster"
  }
  - {
      "name":"dfs.ha.namenodes.ha-cluster",
      "value":"nn1,nn2"
  }
  - {
      "name":"dfs.namenode.rpc-address.ha-cluster.nn1",
      "value":"{{ netinfo.hostname.master }}:{{ hadoop.hdfs_port }}"
  }
  - {
      "name":"dfs.namenode.rpc-address.ha-cluster.nn2",
      "value":"{{ netinfo.hostname.standby }}:{{ hadoop.hdfs_port }}"
  }
  - {
      "name":"dfs.namenode.http-address.ha-cluster.nn1",
      "value":"{{ netinfo.hostname.master }}:50070"
  }
  - {
      "name":"dfs.namenode.http-address.ha-cluster.nn2",
      "value":"{{ netinfo.hostname.standby }}:50070"
  }
  - {
      "name":"dfs.namenode.shared.edits.dir",
      "value":"qjournal://{{ list.qjournal }}/{{ hadoop.dfs.nameservices }}"
  }
  - {
      "name":"dfs.journalnode.edits.dir",
      "value":"{{ config.journalnode_path }}"
  }
  - {
      "name":"dfs.ha.fencing.methods",
      "value":"sshfence"
  }
  - {
      "name":"dfs.ha.fencing.ssh.private-key-files",
      "value":"{{ hadoop.base_path }}/.ssh/id_rsa"
  }
  - {
    "name":"dfs.ha.fencing.ssh.connect-timeout",
    "value":"30000"
  }
  - {
      "name":"dfs.client.failover.proxy.provider.ha-cluster",
      "value":"org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider"
  }
  - {
      "name":"dfs.ha.automatic-failover.enabled",
      "value":"true"
  }
  - {
      "name":"dfs.ha.allow.stale.reads",
      "value":"true"
  }

  # - {
  #    "name":"dfs.datanode.max.xcievers",
  #    "value":"4096"
  #}
  #- {
  #    "name":"dfs.ha.allow.stale.reads",
  #    "value":"true"
  #}
  #- {
  #    "name":"dfs.client.use.datanode.hostname",
  #    "value":"true"
  #}
  #- {
  #    "name":"dfs.datanode.use.datanode.hostname",
  #    "value":"true"
  #}
  #- {
  #    "name":"dfs.block.size",
  #    "value":"134217728"
  #}
  #- {
  #    "name":"dfs.datatnode.address",
  #    "value":"0.0.0.0:9000"
  #}  # Applied first for Hadoop 2.10.2, 9000 was in 3.4.x


mapred_site_properties:
 - {
   "name": "mapreduce.framework.name",
   "value": "yarn"
 }
 - {
   "name": "mapreduce.admin.user.env",
   "value": "HADOOP_MAPRED_HOME=$HADOOP_COMMON_HOME"
 }
 - {
   "name":"yarn.app.mapreduce.am.env",
   "value":"HADOOP_MAPRED_HOME=$HADOOP_COMMON_HOME"
 }


yarn_site_properties:
  - {
    "name": "yarn.nodemanager.aux-services",
    "value": "mapreduce_shuffle"
  }
  - {
    "name":"yarn.log-aggregation-enable",
    "value":"true"
  }
  - {
    "name":"yarn.log-aggregation.retain-seconds",
    "value":"86400"
  }
  - {
    "name":"yarn.resourcemanager.ha.enabled",
    "value":"true"
  }
  - {
    "name":"yarn.resourcemanager.cluster-id",
    "value":"my-yarn-cluster"
  }
  - {
    "name":"yarn.resourcemanager.ha.rm-ids",
    "value":"rm1,rm2,rm3"
  }
  - {
    "name":"yarn.resourcemanager.hostname.rm1",
    "value":"{{ hostvars[groups['workers'][0]].ansible_hostname }}"
  }
  - {
    "name":"yarn.resourcemanager.hostname.rm2",
    "value":"{{ hostvars[groups['workers'][1]].ansible_hostname }}"
  }
  - {
    "name":"yarn.resourcemanager.hostname.rm3",
    "value":"{{ hostvars[groups['workers'][2]].ansible_hostname }}"
  }
  - {
    "name":"yarn.resourcemanager.webapp.address.rm1",
    "value":"{{ hostvars[groups['workers'][0]].ansible_hostname }}:8088"
  }
  - {
    "name":"yarn.resourcemanager.webapp.address.rm2",
    "value":"{{ hostvars[groups['workers'][1]].ansible_hostname }}:8088"
  }
  - {
    "name":"yarn.resourcemanager.webapp.address.rm3",
    "value":"{{ hostvars[groups['workers'][2]].ansible_hostname }}:8088"
  }
  - {
    "name":"yarn.resourcemanager.zk-address",
    "value":"{{ list.zkservers }}"
  }
  - {
    "name":"yarn.resourcemanager.recovery.enabled",
    "value":"true"
  }
  - {
    "name":"yarn.resourcemanager.store.class",
    "value":"org.apache.hadoop.yarn.server.resourcemanager.recovery.ZKRMStateStore"
  }   ###
  - {
    "name":"yarn.resourcemanager.address",
    "value":"{{ netinfo.hostname.master }}:{{ hadoop.yarn.resmgr_port }}"
  }
  - {
    "name":"yarn.resourcemanager.scheduler.address",
    "value":"{{ netinfo.hostname.master }}:{{ hadoop.yarn.resmgr_scheduler_port }}"
  }
  - {
    "name":"yarn.resourcemanager.webapp.address",
    "value":"{{ netinfo.hostname.master }}:{{ hadoop.yarn.resmgr_webapp_port }}"
  }
  - {
    "name": "yarn.resourcemanager.resource-tracker.address",
    "value": "{{ netinfo.hostname.master }}:{{ hadoop.yarn.resmgr_tracker_port }}"
  }
  - {
    "name": "yarn.resourcemanager.admin.address",
    "value": "{{ netinfo.hostname.master }}:{{ hadoop.yarn.resmgr_admin_port }}"
  }
  - {
    "name": "yarn.nodemanager.aux-services.mapreduce.shuffle.class",
    "value": "org.apache.hadoop.mapred.ShuffleHandler"
  }


dashbord_port: 9870
firewall_ports:
  - "{{ dashbord_port}}"
  - "{{ hdfs_port }}"
  - "{{ dfs_namenode_httpport }}"
  - "{{ yarn_resourcemanager_port }}"
  - "{{ yarn_resourcemanager_scheduler_port }}"
  - "{{ yarn_resourcemanager_webapp_port }}"
  - "{{ yarn_resourcemanager_tracker_port }}"
  - "{{ yarn_resourcemanager_admin_port }}"
  - "8485"
  - "50010"

