---
#- name: Delete Public key
#  file:
#    path: "/home/hadoop/.ssh/id_rsa"
#    state: absent

- name: Kill process hold on user directory
  become: true
  shell: |
    nohup pkill -U {{ user }}
    sleep 10

# nohup sh -c "pkill -U <user>; sleep 2;
# nohup fuser -k /home/{{ user }}

- name: Delete "{{ user }}" User
  user:
    name: "{{ user }}"
    state: absent

- name: Delete "{{ group }}" Group
  group:
    name: "{{ group }}"
    state: absent
