---
config:
  base_path: "{{ hadoop.base_path }}"
  path: "{{ hadoop.base_path }}/{{ hive_file_name }}/conf"
  tmp: "{{ hive.tmp_path }}"
  create_path:
    - "{{ hive.tmp_path }}"
  warehouse: "{{ hive.default_path }}/warehouse"
  scratchdir: "{{ hive.default_path }}/tmp"
  querylog_location: "{{ hive.default_path }}/log"
  logging_operation_log_location: "{{ hive.tmp_path }}/{{ hadoop.user }}/operation_logs"


hdfs_path:
  - "{{ config.warehouse }}"
  - "{{ config.scratchdir }}"
  - "{{ config.querylog_location }}"


db:
  type: "postgres"
  conn_driver_name: "org.postgresql.Driver"
  conn_host: "{{ hostvars[groups['database'][0]]['ansible_'~ netdev0]['ipv4']['address'] }}"
  conn_port: "5432"
  conn_dbname: "hive_testdb"
  conn_user_name: "hive_user"
  conn_password: "changeme"


jdbc_connection_string: "jdbc:postgresql://{{ db.conn_host }}:{{ db.conn_port }}/{{ db.conn_dbname }}?ssl=false"


site_properties:
  - {
      "name":"hive.metastore.warehouse.dir",
      "value":"hdfs://{{ hostvars[groups['master'][0]].ansible_hostname }}:{{ hadoop.hdfs_port }}{{ config.warehouse }}"
  }
  - {
      "name":"hive.exec.scratchdir",
      "value":"{{ config.scratchdir }}"
  }
  - {
      "name":"hive.querylog.location",
      "value":"{{ config.querylog_location }}/hadoop"
  }
  - {
      "name":"javax.jdo.option.ConnectionURL",
      "value":"{{ jdbc_connection_string }}"
  }
  - {
    "name":"javax.jdo.option.ConnectionDriverName",
    "value":"{{ db.conn_driver_name }}"
  }
  - {
    "name":"javax.jdo.option.ConnectionUserName",
    "value":"{{ db.conn_user_name }}"
  }
  - {
    "name":"javax.jdo.option.ConnectionPassword",
    "value":"{{ db.conn_password }}"
  }
  - {
    "name":"hive.server2.logging.operation.log.location",
    "value":"{{ config.logging_operation_log_location }}"
  }


firewall_ports:
  - "{{ hive.server_port }}"
  - "{{ hive.hwi_port }}"
  - "{{ hive.metastore_port }}"
