---
#- pause:
#    seconds: 10


- name: Check if Cassandra Cluster Service is Ready
  shell: |
    cqlsh -u {{ _cassandra.user }} -p {{ _cassandra.password }} -e 'describe cluster'
  register: check_cassandra_cluster
  until: check_cassandra_cluster is succeeded
  retries: 10
  delay: 10
  environment:
    PATH: "{{ cassandra_root_dir }}/bin:/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg={{ check_cassandra_cluster }}
  when: print_debug == true


- name: Create Users
  shell: |
    cqlsh -u {{ _cassandra.user }} -p {{ _cassandra.password }} \
    -e "CREATE ROLE {{ item.name }} WITH SUPERUSER = {{ item.su }} AND LOGIN = {{ item.login }} AND PASSWORD = '{{ item.password }}';"
  register: create_users
  environment:
    PATH: "{{ cassandra_root_dir }}/bin:/usr/local/bin:{{ ansible_env.PATH }}"
  with_items: "{{ _cassandra.users }}"
- debug: msg={{ create_users }}
  when: print_debug == true


# https://cassandra.apache.org/doc/stable/cassandra/operating/security.html

