---
- name: Check if Cassandra Cluster Service is Ready
  shell: |
    cqlsh -u {{ _cassandra.user }} -p {{ _cassandra.user }} -e 'describe cluster'
  register: check_cassandra_cluster
  until: check_cassandra_cluster is succeeded
  retries: 10
  delay: 10
  environment:
    PATH: "{{ cassandra_root_dir }}/bin:/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg={{ check_cassandra_cluster }}
  when: print_debug == true


- name: Change Cassandra Password
  shell: |
    cqlsh -u {{ _cassandra.user }} -p {{ _cassandra.user }} -e "ALTER USER cassandra with PASSWORD '{{ _cassandra.password }}';"
  register: change_cassandra_passsword
  environment:
    PATH: "{{ cassandra_root_dir }}/bin:/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg={{ change_cassandra_passsword }}
  when: print_debug == true

