---
- name: Check if Cassandra Cluster Service is Ready
  shell: |
    cqlsh -u {{ _cassandra.users.0.name }} -p {{ _cassandra.users.0.password }} -e 'describe cluster'
  register: check_cassandra_cluster
  until: check_cassandra_cluster is succeeded
  retries: 10
  delay: 10
  environment:
    PATH: "{{ cassandra_root_dir }}/bin:/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg={{ check_cassandra_cluster }}
  when: print_debug == true


- name: Disable Cassandra User
  shell: |
    cqlsh -u {{ _cassandra.users.0.name }} -p {{ _cassandra.users.0.password  }} \
    -e "ALTER ROLE cassandra WITH SUPERUSER = false AND LOGIN = false;"
  register: disable_cassandra_user
  environment:
    PATH: "{{ cassandra_root_dir }}/bin:/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg={{ disable_cassandra_user }}
  when: print_debug == true

