---
- name: Create Cassandra Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ _cassandra.user }}"
    group: "{{ _cassandra.group }}"
  with_items:
    - "{{ _cassandra.user_home }}/.cassandra"   # Hidden
    - "{{ _cassandra.dir.base }}"               # Base Data
    - "{{ _cassandra.dir.commit }}"             # Commit Log
    - "{{ _cassandra.dir.logs }}"               # Log Directory
    - "{{ _cassandra.dir.data }}"               # Data Directory
    - "{{ _cassandra.dir.data }}/cdc_raw"       # CDC Raw Data Directory

