---
- name: Copy Cassandra Configurations
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    force: "{{ item.force }}"
  with_items:
    - { src: "cassandra.yaml.j2", dest: "{{ cassandra_application_path }}/conf/cassandra.yaml", mode: "0644", owner: "{{ _cassandra.user }}", group: "{{ _cassandra.group }}", force: "yes" }
    - { src: "cassandra-env.sh.j2", dest: "{{ cassandra_application_path }}/conf/cassandra-env.sh", mode: "0755", owner: "{{ _cassandra.user }}", group: "{{ _cassandra.group }}", force: "yes" }
    - { src: "cqlsh.j2", dest: "/home/cassandra/.cassandra/cqlsh", mode: "0644", owner: "{{ _cassandra.user }}", group: "{{ _cassandra.group }}", force: "yes" }
    - { src: "cassandra.systemd.j2", dest: "/etc/systemd/system/cassandra.service", mode: "0644", owner: "{{ _cassandra.user }}", group: "{{ _cassandra.group }}", force: "yes" }


- name: Reload Systemd Daemon
  systemd:
    daemon_reload: yes


- name: Insert Executable Binary Path into .bashrc
  lineinfile:
    path: "{{ item }}"
    line: "export PATH={{ cassandra_application_path }}/bin:{{ cassandra_application_path }}/sbin:$PATH"
  with_items:
    - "/home/{{ _cassandra.user }}/.bashrc"
    - "/root/.bashrc"

