---
- name: Copy Cassandra Configuration
  template: src=cassandra.yaml.j2 dest={{ cassandra_application_path }}/conf/cassandra.yaml mode=0644 owner={{ _cassandra.user }} group={{ _cassandra.group }} force=yes


- name: Copy Cassandra Env
  template: src=cassandra-env.sh.j2 dest={{ cassandra_application_path }}/conf/cassandra-env.sh mode=0755 owner={{ _cassandra.user }} group={{ _cassandra.group }} force=yes


- name: Copy Cqlsh Configuration
  template: src=cqlsh.j2 dest=/home/cassandra/.cassandra/cqlsh mode=0644 owner={{ _cassandra.user }} group={{ _cassandra.group }} force=yes


- name: Copy Cassandra Systemd
  template: src=cassandra.systemd.j2 dest=/etc/systemd/system/cassandra.service owner=root group=root mode=644 force=yes


- name: Reload Systemd Daemon
  shell: "systemctl daemon-reload"


- name: Insert Executable Binary Path into .bashrc
  lineinfile:
    path: "{{ item }}"
    line: "export PATH={{ cassandra_application_path }}/bin:{{ cassandra_application_path }}/sbin:$PATH"
  with_items:
    - "/home/{{ _cassandra.user }}/.bashrc"
    - "/root/.bashrc"

