---
- name: Copy Directory for Cassandra Example Queries
  file:
    path: "{{ _cassandra.user_home }}/cqlsh"
    state: directory
    owner: "{{ _cassandra.user }}"
    group: "{{ _cassandra.user }}"
    mode: 0755


#- name: Copy Cassandra Example Queries
#  synchronize:
#    dest: "{{ _cassandra.user_home }}/cqlsh"
#    src: "{{ role_path }}/files/cqlsh"
#    rsync_opts:
#      - "-e ssh"          # "-e ssh -i ~/.ssh/id_rsa.pub"
#    ssh_args:
#      - "-p {{ _cassandra.password }} -o StrictHostKeyChecking=no"
#  register: copy_example_queries
#- debug: msg={{ copy_example_queries }}
#when: print_debug == true


- name: Copy Cassandra Example Queries
  shell: |
    rsync -a --rsh='/usr/bin/sshpass -p {{ _cassandra.password }} ssh -o StrictHostKeyChecking=no' \
    {{ role_path }}/templates/cqlsh {{ _cassandra.user }}@{{ hostvars[inventory_hostname][_netdev]['ipv4']['address'] }}:{{ _cassandra.user_home }}
  register: copy_example_queries
  delegate_to: localhost
  failed_when: copy_example_queries.rc != 0
  # when: inventory_hostname in groups['master']

