---
- name: Delete Config/Log/Data Files for Cassandra
  file:
    path: "{{ item }}"
    state: absent
  ignore_errors: true
  with_items:
    - "/home/cassandra/.cassandra/cqlsh"
    - "{{ _cassandra.base_path }}/apache-cassandra"
    - "{{ _cassandra.base_path }}/apache-cassandra-{{ cassandra_version }}"
    - "{{ _cassandra.download_path }}/{{ cassandra_package_name }}"
    - "{{ _cassandra.dir.data }}"
    - "{{ _cassandra.dir.commit }}"
    - "{{ _cassandra.dir.logs }}"
    - "{{ _cassandra.dir.base }}"
    - "/etc/systemd/system/cassandra.service"


- name: Remove a Line Including PATH Variable
  lineinfile:
    path: "{{ item }}"
    regexp: "^export PATH=(.*)cassandra(.*)PATH$"
    state: absent
  register: remove_cassandra_path
  ignore_errors: true
  with_items:
    - "/home/{{ _cassandra.user }}/.bashrc"
    - "/root/.bashrc"


- name: Reload Systemd Services
  systemd:
    daemon_reload: yes
  register: systemd_reloaded
  ignore_errors: true

