---
- pause:
    seconds: 20


- name: Change Cassandra Password
  shell: |
    cqlsh -u {{ _cassandra.user }} -p {{ _cassandra.user }} -e "ALTER USER cassandra with PASSWORD '{{ _cassandra.password }}';"
  register: change_cassandra_passsword
  # ignore_errors: true
  environment:
    PATH: "{{ cassandra_root_dir }}/bin:/usr/local/bin:{{ ansible_env.PATH }}"
- debug: msg={{ change_cassandra_passsword }}
  when: print_debug == true

