---
- name: Set Cassandra Commit Log Directory
  file: path={{ _cassandra.dir.commit }} state=directory owner={{ _cassandra.user }} group={{ _cassandra.group }}


- name: Set Cassandra Log Directory
  file: path={{ _cassandra.dir.logs }} state=directory owner={{ _cassandra.user }} group={{ _cassandra.group }}


- name: Set Cassandra Data Directory
  file: path={{ _cassandra.dir.data }} state=directory owner={{ _cassandra.user }} group={{ _cassandra.group }}


- name: Set Cassandra CDC Raw Data Directory
  file: path={{ _cassandra.dir.data }}/cdc_raw state=directory owner={{ _cassandra.user }} group={{ _cassandra.group }}


- name: Set Cassandra Configuration
  template: src=cassandra.yml.j2 dest={{ cassandra_application_path }}/conf/cassandra.yml mode=0644 owner={{ _cassandra.user }} group={{ _cassandra.group }} force=yes


- name: Start Cassandra
  template: src=cassandra.systemd.j2 dest=/etc/systemd/system/cassandra.service owner=root group=root mode=644 force=yes


- name: Reload Systemd Daemon
  shell: "systemctl daemon-reload"
  notify: Restart Cassandra

