---
- name: Check OS ( Cassandra )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: install, uninstall, add, setup, remove, config, create, delete, start, stop
  when: inventory_hostname not in groups['database']


- name: Setup Cassandra
  import_tasks: install.yml
  tags: setup, install
  when: (( bin is defined and bin == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname not in groups['database']


- name: Add Users
  import_tasks: add-users.yml
  tags: add, create, install
  when: (( users is defined and users == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname in groups['master']


- name: Delete Users
  import_tasks: delete-users.yml
  tags: remove, delete, uninstall
  when: (( users is defined and users == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname in groups['master']


- name: Disable Cassandra Users
  import_tasks: disable-cassandra-user.yml
  tags: disable
  when: (( admin is defined and admin == true ) and inventory_hostname in groups['master']


- name: Remove Cassandra
  import_tasks: uninstall.yml
  tags: remove, uninstall
  when: (( bin is defined and bin == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname not in groups['database']

