# https://about-cassandra.com/install-apache-cassandra-via-tarball/
# https://github.com/wireapp/ansible-cassandra
# https://www.pythian.com/blog/technical-track/an-introductory-guide-on-deploying-cassandra-database-using-ansible
