---
- name: Check OS ( Cassandra )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: install, uninstall, setup, remove, config, create, delete, start, stop
  when: inventory_hostname not in groups['database']


- name: Install Cassandra
  import_tasks: install-cassandra.yml
  tags: setup, install
  when: (( cassandra is defined and cassandra == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname not in groups['database']


- name: Config Cassandra
  import_tasks: config-cassandra.yml
  tags: config, install
  when: (( cassandra is defined and cassandra == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname not in groups['database']


- name: Start Cassandra
  import_tasks: start-cassandra.yml
  tags: start, install
  when: (( cassandra is defined and cassandra == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname in groups['master']


- name: Stop Cassandra
  import_tasks: stop-cassandra.yml
  tags: stop, uninstall
  when: (( cassandra is defined and cassandra == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname in groups['master']


- name: Uninstall Cassandra
  import_tasks: uninstall.yml
  tags: delete, remove, uninstall
  when: (( cassandra is defined and cassandra == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname not in groups['database']


# https://about-cassandra.com/install-apache-cassandra-via-tarball/
# https://github.com/wireapp/ansible-cassandra
# https://www.pythian.com/blog/technical-track/an-introductory-guide-on-deploying-cassandra-database-using-ansible

