---
- name: Check OS ( Cassandra )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: install, uninstall, add, setup, remove, config, create, delete, start, stop, copy, change, enable, disable
  when: inventory_hostname not in groups['database']


- name: Setup Cassandra System User
  import_tasks: 01-add-sys-user.yml
  tags: add, create, install
  when: (( sysuser is defined and sysuser == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname not in groups['database']


- name: Setup Cassandra Software Binary
  import_tasks: 02-setup-cassandra.yml
  tags: setup, install
  when: (( bin is defined and bin == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname not in groups['database']


- name: Setup Cassandra Directory
  import_tasks: 03-create-directory.yml
  tags: create, setup, install
  when: (( dir is defined and dir == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname not in groups['database']


- name: Setup Cassandra Configuration
  import_tasks: 04-config-cassandra.yml
  tags: setup, install
  when: (( config is defined and config == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname not in groups['database']


- name: Start Cassandra Service
  import_tasks: 05-start-cassandra.yml
  tags: start, install
  when: (( serivce is defined and service == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname not in groups['database']


- name: Copy Query Examples
  import_tasks: 06-copy-queries.yml
  tags: copy, install
  when: (( examples is defined and examples == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname in groups['master']


- name: Change Cassandra Password
  import_tasks: change-admin-password.yml
  tags: change, install
  when: (( passwd is defined and passwd == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname in groups['master']


- name: Add Cassandra Users
  import_tasks: add-users.yml
  tags: add, create, install
  when: (( users is defined and users == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname in groups['master']


- name: Disable Cassandra Users
  import_tasks: disable-cassandra-user.yml
  tags: disable, install
  when: (( admin is defined and admin == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname in groups['master']


- name: Delete Cassandra Users
  import_tasks: delete-users.yml
  tags: remove, delete, uninstall
  when: (( users is defined and users == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname in groups['master']


- name: Stop Cassandra Service
  import_tasks: 41-stop-cassandra.yml
  tags: stop, uninstall
  when: (( service is defined and service == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname not in groups['database']


- name: Delete Cassandra Configurations
  import_tasks: 42-delete-config.yml
  tags: remove, delete, uninstall
  when: (( config is defined and config == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname not in groups['database']


- name: Delete Cassandra System Users
  import_tasks: 43-remove-sysuser.yml
  tags: remove, delete, uninstall
  when: (( sysuser is defined and sysuser == true ) or ( cassandra_all is defined and cassandra_all == true )) and inventory_hostname not in groups['database']

