---
- name: Get Network Interface Name from Prefix of IP Addresses
  set_fact:
    netdev0: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', _cassandra.net.ipaddr0 ) | map(attribute='device') | first }}"
    netdev2: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', _cassandra.net.ipaddr2 ) | map(attribute='device') | first }}"
    # netdev1: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', cassandra.net.ipaddr1 ) | map(attribute='device') | first }}"


- name: Get IP Address from Network Device Name
  set_fact:
    ipaddr0: "{{ hostvars[inventory_hostname]['ansible_'~netdev0].ipv4.address }}"
    ipaddr2: "{{ hostvars[inventory_hostname]['ansible_'~netdev2].ipv4.address }}"
    # ipaddr1: "{{ hostvars[inventory_hostname]['ansible_'~netdev1].ipv4.address }}"


- name: Define Fact for cassandra Version
  set_fact:
    cassandra_file_name: "cassandra-{{ _cassandra.major_version }}.{{ _cassandra.minor_version }}.{{ _cassandra.patch_version }}-bin-hadoop{{ _hadoop.major_version }}"
    cassandra_root_dir: "{{ _cassandra.base_path }}/cassandra-{{ _cassandra.major_version }}.{{ _cassandra.minor_version }}.{{ _cassandra.patch_version }}-bin-hadoop{{ _hadoop.major_version }}"
    hadoop_version: "{{ _hadoop.major_version }}.{{ _hadoop.minor_version }}.{{ _hadoop.patch_version }}"
    cassandra_version: "{{ _cassandra.major_version }}.{{ _cassandra.minor_version }}.{{ _cassandra.patch_version }}"


- name: Set Default Network Device and Address
  set_fact:
    netdev: "{{ netdev2 }}"
    _netdev: "ansible_{{ netdev2 }}"
    _ipaddr: "{{ ipaddr2 }}"

