---
- name: Stop All Spark Services
  become_user: "{{ _spark.user }}"
  shell: |
    {{ spark_root_dir }}/sbin/{{ item }}
  register: start_spark_service
  args:
    executable: /bin/bash
    chdir: "{{ _spark.base_path }}"
  environment:
    PATH: "{{ spark_root_dir }}/sbin:{{ spark_root_dir }}/bin:/usr/local/bin:{{ ansible_env.PATH }}"
  with_items:
    - "stop-thriftserver.sh"
    - "stop-mesos-shuffle-service.sh"
    - "stop-workers.sh"
    - "stop-master.sh"

