---
- name: Enable and Start Firewalld
  systemd:
    name: firewalld
    enabled: yes
    state: started
  when: inventory_hostname in groups['master'] or inventory_hostname in groups['standby'] or inventory_hostname in groups['workers']


- name: Reset Ruleset for Public Zone In Firewalld
  shell: |
    firewall-cmd --load-zone-defaults=public --permanent
    firewall-cmd --reload
  when: inventory_hostname in groups['master'] or inventory_hostname in groups['standby'] or inventory_hostname in groups['workers']


- name: Set Firewalld Port Policy For Name nodes
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    zone: public
    immediate: yes
  loop: "{{ nn_firewall_ports }}"
  when: inventory_hostname in groups['master'] or inventory_hostname in groups['standby']


- name: Set Firewalld Port Policy For Data nodes
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    zone: public
    immediate: yes
  loop: "{{ dn_firewall_ports }}"
  when: inventory_hostname in groups['workers']


- name: Set Firewalld Port Policy For Common
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    zone: public
    immediate: yes
  loop: "{{ common_firewall_ports }}"
  when: inventory_hostname in groups['master'] or inventory_hostname in groups['standby'] or inventory_hostname in groups['workers']

#  notify: Restart Firewalld
#  when: ( inventory_hostname in groups['master'] or inventory_hostname in groups['standby'] or inventory_hostname in groups['workers'] )

