rh_common_dep_pkgs: "epel-release,readline-devel,libicu-devel,rsyslog,rsync,postgresql-devel"

remove_rh_common_dep_pkgs: "epel-release,readline-devel,libicu-devel,rsyslog,rsync,postgresql-devel"

rh7_dep_pkgs: "tk"
rh8_dep_pkgs: "tk"
rh9_dep_pkgs: "tk"

rh7_python_pkgs: "tcl"
rh8_python_pkgs: "tcl"
rh9_python_pkgs: "tcl,python3-mod_wsgi,httpd-devel"

