---
- name: Add Hadoop Master Metrics into Ganglia
  become_user: hadoop
  lineinfile:
    dest: "{{ _hadoop.base_path }}/hadoop-{{ hadoop_version }}/etc/hadoop/hadoop-metrics2.properties"
    line: '{{ item.line }}'
  with_items: "{{ _hadoop_master_metrics2_properties }}"
  when: inventory_hostname in groups['master']


- name: Add Hadoop Slave Metrics into Ganglia
  become_user: hadoop
  lineinfile:
    dest: "{{ _hadoop.base_path }}/hadoop-{{ hadoop_version }}/etc/hadoop/hadoop-metrics2.properties"
    line: '{{ item.line }}'
  with_items: "{{ _hadoop_slave_metrics2_properties }}"
  when: inventory_hostname in groups['standby']


- name: Stop Hadoop
  import_tasks: ext/stop-hadoop.yml
  when: inventory_hostname not in groups['database']


- name: Start Hadoop
  import_tasks: ext/start-hadoop.yml
  when: inventory_hostname not in groups['database']

