---
- name: Install Ganglia Meta Deamon and RRDTool
  package: name={{ item }} state=present
  with_items:
    - ganglia-gmetad
    - rrdtool
    - rrdtool-devel


- name: Configure Gmetad.conf In /etc/ganglia/gmetad.conf
  template: src=gmetad.conf.j2 dest=/etc/ganglia/gmetad.conf owner=root group=root mode=0644
  notify:
    - Restart Gmetad

