---
- name: Check OS ( Ganglia )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: install, uninstall, enable, disable, config, create, delete, setup, remove


- name: Enable SELinux
  import_tasks: ext/enable-selinux.yml
  tags: enable, install
  when: inventory_hostname in groups['database'] and (( selinux is defined and selinux == true ) or ( ganglia_all is defined and ganglia_all == true ))


- name: Install Common Prerequisties Packages
  import_tasks: install-deps-pkgs.yml
  tags: setup, install
  when: ( pkgs is defined and pkgs == true ) or ( ganglia_all is defined and ganglia_all == true )


- name: Install Ganglia Gmond
  import_tasks: install-gmond.yml
  tags: setup, install
  when: ( inventory_hostname not in groups['database'] ) and (( gmond is defined and gmond == true ) or ( ganglia_all is defined and ganglia_all == true ))


- name: Install Ganglia Mmetad
  import_tasks: install-gmetad.yml
  tags: setup, install
  when: inventory_hostname in groups['database'] and (( gmetad is defined and gmetad == true ) or ( ganglia_all is defined and ganglia_all == true ))


- name: Install Ganglia Web
  import_tasks: install-web.yml
  tags: setup, install
  when: inventory_hostname in groups['database'] and  (( web is defined and web == true ) or ( ganglia_all is defined and ganglia_all == true ))


- name: Configure Hadoop Metrics
  import_tasks: config-hadoop-metrics.yml
  tags: config, install
  when: inventory_hostname not in groups['database'] and (( metrics is defined and metrics == true ) or ( ganglia_all is defined and ganglia_all == true ))


- name: Disable Firewall
  import_tasks: ext/disable-firewall.yml
  tags: disable, install
  when: inventory_hostname in groups['database'] and (( firewall is defined and firewall == true ) or ( ganglia_all is defined and ganglia_all == true ))


- name: Uninstall Ganglia Web
  import_tasks: uninstall-web.yml
  tags: delete, remove, uninstall
  when: inventory_hostname in groups['database'] and (( web is defined and web == true ) or ( ganglia_all is defined and ganglia_all == true ))


- name: Uninstall Ganglia Gmetad
  import_tasks: uninstall-gmetad.yml
  tags: delete, remove, uninstall
  when: inventory_hostname in groups['database'] and (( gmetad is defined and gmetad == true ) or ( ganglia_all is defined and ganglia_all == true ))


- name: Uninstall Ganglia GMond
  import_tasks: uninstall-gmond.yml
  tags: delete, remove, uninstall
  when: inventory_hostname not in groups['database'] and (( gmond is defined and gmond == true ) or ( ganglia_all is defined and ganglia_all == true ))


- name: Uninstall Hadoop Metrics
  import_tasks: uninstall-hadoop-metrics.yml
  tags: remove, delete, uninstall
  when: inventory_hostname not in groups['database'] and (( metrics is defined and metrics == true ) or ( ganglia_all is defined and ganglia_all == true ))


- name: Uninstall Common Prerequisties Packages
  import_tasks: uninstall-deps-pkgs.yml
  tags: remove, delete, uninstall
  when: ( pkgs is defined and pkgs == true ) or ( ganglia_all is defined and ganglia_all == true )


- name: Enable Firewall
  import_tasks: ext/enable-firewall.yml
  tags: enable, install
  when: inventory_hostname in groups['database'] and (( firewall is defined and firewall == true ) or ( ganglia_all is defined and ganglia_all == true ))


- name: Disable SELinux
  import_tasks: ext/disable-selinux.yml
  tags: disable, uninstall
  when: inventory_hostname in groups['database'] and (( selinux is defined and selinux == true ) or ( ganglia_all is defined and ganglia_all == true ))


- name: Start Hadoop
  import_tasks: ext/start-hadoop.yml
  tags: start
  when: inventory_hostname in groups['database'] and ( hdfs is defined and hdfs == true )


- name: Stop Hadoop
  import_tasks: ext/stop-hadoop.yml
  tags: stop
  when: inventory_hostname in groups['database'] and ( hdfs is defined and hdfs == true )

