---
# For now fail if it's not a Red Hat based system
- name: Check OS ( Ganglia )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: install, uninstall, enable, disable, config, create, delete, setup, remove


- name: Disable Firewall
  import_tasks: disable-firewall.yml
  tags: disable, install
  when: (( firewall is defined and firewall == true ) or ( ganglia_all is defined and ganglia_all == true )) and inventory_hostname not in groups['database']


- name: Install Ganglia Monitor
  import_tasks: install-monitor.yml
  tags: setup, install
  when: (( monitor is defined and monitor == true ) or ( ganglia_all is defined and ganglia_all == true )) and inventory_hostname not in groups['database']


- name: Install Ganglia Mmetad
  import_tasks: install-gmetad.yml
  tags: setup, install
  when: (( gmetad is defined and gmetad == true ) or ( ganglia_all is defined and ganglia_all == true )) and inventory_hostname in groups['master']


- name: Install Ganglia Web
  import_tasks: install-web.yml
  tags: setup, install
  when: (( web is defined and web == true ) or ( ganglia_all is defined and ganglia_all == true )) and inventory_hostname in groups['master']


- name: Configure Hadoop Metrics
  import_tasks: config-hadoop-metrics.yml
  tags: config, install
  when: (( metrics is defined and metrics == true ) or ( ganglia_all is defined and ganglia_all == true )) and inventory_hostname not in groups['database']


- name: Uninstall Ganglia Web/Metad/Monitor
  import_tasks: uninstall.yml
  tags: delete, remove, uninstall
  when: (( ganglia is defined and ganglia == true ) or ( ganglia_all is defined and ganglia_all == true )) and inventory_hostname not in groups['database']


- name: Remove Hadoop Metrics
  import_tasks: remove-hadoop-metrics.yml
  tags: delete, remove, uninstall
  when: (( metrics is defined and metrics == true ) or ( ganglia_all is defined and ganglia_all == true )) and inventory_hostname not in groups['database']


- name: Enable Firewall
  import_tasks: enable-firewall.yml
  tags: enable, uninstall
  when: (( firewall is defined and firewall == true ) or ( ganglia_all is defined and ganglia_all == true )) and inventory_hostname not in groups['database']

