---
# For now fail if it's not a Red Hat based system
- name: Check OS ( Ganglia )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags:
    - install
    - uninstall


- name: Disable Firewall
  import_tasks: disable-firewall.yml
  tags: install
  when: ganglia.firewall == true


- name: Install Ganglia Monitor
  import_tasks: install-monitor.yml
  tags: install
  when: inventory_hostname in groups['master'] or inventory_hostname in groups['standby'] or inventory_hostname in groups['workers']


- name: Install Ganglia Mmetad
  import_tasks: install-gmetad.yml
  tags: install
  when: inventory_hostname in groups['master']


- name: Install Ganglia Web
  import_tasks: install-web.yml
  tags: install
  when: inventory_hostname in groups['master']


- name: Configure Hadoop Metrics
  import_tasks: config-hadoop-metrics.yml
  tags: install
  when: inventory_hostname in groups['master'] or inventory_hostname in groups['standby'] or inventory_hostname in groups['workers']


- name: Uninstall Ganglia Web/Metad/Monitor
  import_tasks: uninstall.yml
  tags: uninstall
  when: inventory_hostname in groups['master'] or inventory_hostname in groups['standby'] or inventory_hostname in groups['workers']


- name: Remove Hadoop Metrics
  import_tasks: remove-hadoop-metrics.yml
  tags: uninstall
  when: inventory_hostname in groups['master'] or inventory_hostname in groups['standby'] or inventory_hostname in groups['workers']


- name: Enable Firewall
  import_tasks: enable-firewall.yml
  tags: uninstall
  when: spark.firewall == true
