---
- name: Get Network Interface Name from Prefix of IP Addresses
  set_fact:
    netdev0: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', ganglia.net.ipaddr0 ) | map(attribute='device') | first }}"
    netdev1: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', ganglia.net.ipaddr1 ) | map(attribute='device') | first }}"


- name: Get IP Address from Network Device Name
  set_fact:
    ipaddr0: "{{ hostvars[inventory_hostname]['ansible_'~netdev0].ipv4.address }}"
    ipaddr1: "{{ hostvars[inventory_hostname]['ansible_'~netdev1].ipv4.address }}"


- name: Define Fact for Ganglia Version
  set_fact:
    ganglia_web_file_name: "ganglia-web-{{ ganglia.web.major_version }}.{{ ganglia.web.minor_version }}.{{ ganglia.web.patch_version }}"
    ganglia_web_version: "{{ ganglia.web.major_version }}.{{ ganglia.web.minor_version }}.{{ ganglia.web.patch_version }}"
    ganglia_web_root_dir: "{{ ganglia.base_path }}/ganglia-web-{{ ganglia.web.major_version }}.{{ ganglia.web.minor_version }}.{{ ganglia.web.patch_version }}"
    hadoop_version: "{{ hadoop.major_version }}.{{ hadoop.minor_version }}.{{ hadoop.patch_version }}"

