---
- name: Get Network Interface Name from Prefix of IP Addresses
  set_fact:
    netdev0: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', _ganglia.net.ipaddr0 ) | map(attribute='device') | first }}"
    netdev1: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', _ganglia.net.ipaddr2 ) | map(attribute='device') | first }}"
    # netdev1: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', _ganglia.net.ipaddr1 ) | map(attribute='device') | first }}"


- name: Get IP Address from Network Device Name
  set_fact:
    ipaddr0: "{{ hostvars[inventory_hostname]['ansible_'~netdev0].ipv4.address }}"
    ipaddr2: "{{ hostvars[inventory_hostname]['ansible_'~netdev2].ipv4.address }}"
    # ipaddr1: "{{ hostvars[inventory_hostname]['ansible_'~netdev1].ipv4.address }}"


- name: Define Fact for Ganglia Version
  set_fact:
    ganglia_web_file_name: "ganglia-web-{{ _ganglia.web.major_version }}.{{ _ganglia.web.minor_version }}.{{ _ganglia.web.patch_version }}"
    ganglia_web_version: "{{ _ganglia.web.major_version }}.{{ _ganglia.web.minor_version }}.{{ _ganglia.web.patch_version }}"
    ganglia_web_root_dir: "{{ _ganglia.base_path }}/ganglia-web-{{ _ganglia.web.major_version }}.{{ _ganglia.web.minor_version }}.{{ _ganglia.web.patch_version }}"
    hadoop_version: "{{ _hadoop.major_version }}.{{ _hadoop.minor_version }}.{{ _hadoop.patch_version }}"


- name: Set Default Network Device and Address
  set_fact:
    netdev: "{{ netdev2 }}"
    _netdev: "ansible_{{ netdev2 }}"
    _ipaddr: "{{ ipaddr2 }}"

