---
- name: Stop Apache HTTPd Server and PHP-FPM and Gmetad
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - gmond
    - gmetad
    - httpd
    - php-fpm
  ignore_errors: true


- name: Uninstall Ganglia Web Dependencies
  package: name={{ item }} state=absent
  with_items:
    - httpd
    - php
    - rrdtool
    - rrdtool-devel
  ignore_errors: true


- name: Delete Ganglia-Web at /var/www/ganglia
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/var/www/ganglia"
    - "/var/lib/ganglia/rrds"
    - "/var/lib/ganglia"
    - "/var/lib/ganglia-web"


- name: Uninstall Ganglia Meta Deamon and RRDTool
  package: name={{ item }} state=absent
  ignore_errors: true
  with_items:
    - ganglia-web
    - ganglia-gmetad
    - rrdtool
    - rrdtool-devel


- name: Delete /etc/ganglia/gmetad.conf
  file:
    path: "{{ item }}"
    state: absent
  ignore_errors: true
  with_items:
    - "/etc/ganglia/gmetad.conf"
