---
- name: Uninstall Ganglia Meta Deamon and RRDTool
  package: name={{ item }} state=absent
  register: uninstall_gmetad
  ignore_errors: true
  with_items:
    - rrdtool-devel
    - rrdtool
    - ganglia-gmetad


- name: Delete Gmetad.conf
  file: path=/etc/ganglia/gmetad.conf state=absent
  register: delete_gmetad_conf
  ignore_errors: true

