---
- name: Stop Gmond
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  ignore_errors: true
  with_items:
    - gmond


- name: Uninstall Ganglia Monitor and Required Packages
  package: name={{ item }} state=absent
  ignore_errors: true
  with_items:
    - sysstat
    - php-cli
    - ganglia-gmond
    - hddtemp


- name: Delete /etc/ganglia/gmond.conf
  file:
    path: "{{ item }}"
    state: absent
  ignore_errors: true
  with_items:
    - "/etc/ganglia/gmond.conf"
    - "/usr/local/sbin/device-metrics.php"
    - "/etc/cron.d/device-metrics"


- name: Reload Systemd Daemon
  systemd:
    daemon_reload: yes
  register: reload_sysemd_daemon
  async: 60
  poll: 5

