# https://github.com/dogukancagatay/docker-cassandra-web
- name: Pull Cassndra Web Docker Image
  shell: |
    docker pull docker.io/dcagatay/cassandra-web
  register: pull_docker_image


- name: Run Cassndra Web Docker Image
  shell: |
    docker run -d -p 3030:3000 -e CASSANDRA_HOST_IPS=192.168.2.191 -e CASSANDRA_PORT=9042 -e CASSANDRA_USERNAME=jomoon \
    -e CASSANDRA_PASSWORD=changeme dcagatay/cassandra-web
  register: run_docker_image


- name: List Docker Processes
  shell: |
    docker ps
  register: list_docker_ps


# From Sources - Not OK Yet
# git clone https://github.com/avalanche123/cassandra-web
# cd cassandra-web/
# gem install cassandra-web
# bundle exec rake rails:update:bin
# rails app:update:bin
# gem install bundler -v 1.0.10
# cassandra-web

# https://github.com/avalanche123/cassandra-web

# From Sources - Not OK Yet
# mkdir cassandra-web
# cd cassandra-web
# wget https://github.com/orzhaha/cassandra-web/archive/tags/v1.1.5.tar.gz
# tar xvzf v1.1.5.tar.gz
# cd client
# npm install --force
# npm run build




#
# git clone https://github.com/orzhaha/cassandra-web
# cd client
# npm install --force
# npm install --legacy-peer-deps
# npm config set legacy-peer-deps true
# export NODE_OPTIONS=--openssl-legacy-provider
# npm run build

# vi ./service/config.yaml
# HOST_PORT: ":8083"
# READ_ONLY: false
#
#CASSANDRA_HOST: 192.168.2.191
#CASSANDRA_PORT: 9042
#CASSANDRA_USERNAME: jomoon
#CASSANDRA_PASSWORD: changeme
#
#APP_PATH:

# npm run serve

