---
- name: Install OpenJDK package
  yum: name={{ item }} state=present
  with_items:
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
    - java-11-openjdk
    - java-11-openjdk-devel
    - java-17-openjdk
    - java-17-openjdk-devel
    - tar
#    - "{{ java_packages }}"

- name: Copy Java Home Script
  template: src=java_home.sh dest=/etc/profile.d

- name: Set Java Home Script
  shell: source /etc/profile.d/java_home.sh
