_download_url: http://heanet.dl.sourceforge.net/project/ganglia/ganglia-web/3.5.12/ganglia-web-3.5.12.tar.gz

#hadoop_master_metrics2_properties:
#  - "*.sink.ganglia.class=org.apache.hadoop.metrics2.sink.ganglia.GangliaSink31"
#  - "*.sink.ganglia.period=10"
#  - "*.sink.ganglia.slope=jvm.metrics.gcCount=zero,jvm.metrics.memHeapUsedM=both"
#  - "*.sink.ganglia.dmax=jvm.metrics.threadsBlocked=70,jvm.metrics.memHeapUsedM=40"
#  - "namenode.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649"
#  - "resourcemanager.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649"
#  - "datanode.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649"
#  - "nodemanager.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649"
#  - "maptask.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649"
#  - "reducetask.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649"
#  # 'master' refers to the hostname of Hadoop master node.
#  # or could be the ip address of the node that has Ganglia gmetad installed.
#
#hadoop_slave_metrics2_properties:
#  - "*.sink.ganglia.class=org.apache.hadoop.metrics2.sink.ganglia.GangliaSink31"
#  - "*.sink.ganglia.period=10"
#  - "*.sink.ganglia.slope=jvm.metrics.gcCount=zero,jvm.metrics.memHeapUsedM=both"
#  - "*.sink.ganglia.dmax=jvm.metrics.threadsBlocked=70,jvm.metrics.memHeapUsedM=40"
#  - "namenode.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649"
#  - "resourcemanager.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649"
#  - "datanode.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649"
#  - "nodemanager.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649"
#  - "maptask.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649"
#  - "reducetask.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649"
#  # 'master' refers to the hostname of Hadoop master node.
#  # or could be the ip address of the node that has Ganglia gmetad installed.


_hadoop_master_metrics2_properties:
  - { regexp: "^(.*).sink.ganglia.class=*", line: "*.sink.ganglia.class=org.apache.hadoop.metrics2.sink.ganglia.GangliaSink31" }
  - { regexp: "^(.*).sink.ganglia.period=*", line: "*.sink.ganglia.period=10" }
  - { regexp: "^(.*).sink.ganglia.slope=*", line: "*.sink.ganglia.slope=jvm.metrics.gcCount=zero,jvm.metrics.memHeapUsedM=both" }
  - { regexp: "^(.*).sink.ganglia.dmax=*", line: "*.sink.ganglia.dmax=jvm.metrics.threadsBlocked=70,jvm.metrics.memHeapUsedM=40" }
  - { regexp: "^namenode.sink.ganglia.servers=*", line: "namenode.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649" }
  - { regexp: "^resourcemanager.sink.ganglia.servers=*", line: "resourcemanager.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649" }
  - { regexp: "^datanode.sink.ganglia.servers=*", line: "datanode.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649" }
  - { regexp: "^nodemanager.sink.ganglia.servers=*", line: "nodemanager.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649" }
  - { regexp: "^maptask.sink.ganglia.servers=*", line: "maptask.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649" }
  - { regexp: "^reducetask.sink.ganglia.servers=*", line: "reducetask.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649" }


_hadoop_slave_metrics2_properties:
  - { regexp: "^(.*).sink.ganglia.class=*", line: "*.sink.ganglia.class=org.apache.hadoop.metrics2.sink.ganglia.GangliaSink31" }
  - { regexp: "^(.*).sink.ganglia.period=*", line: "*.sink.ganglia.period=10" }
  - { regexp: "^(.*).sink.ganglia.slope=*", line: "*.sink.ganglia.slope=jvm.metrics.gcCount=zero,jvm.metrics.memHeapUsedM=both" }
  - { regexp: "^(.*).sink.ganglia.dmax=*", line: "*.sink.ganglia.dmax=jvm.metrics.threadsBlocked=70,jvm.metrics.memHeapUsedM=40" }
  - { regexp: "^namenode.sink.ganglia.servers=*", line: "namenode.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649" }
  - { regexp: "^resourcemanager.sink.ganglia.servers=*", line: "resourcemanager.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649" }
  - { regexp: "^datanode.sink.ganglia.servers=*", line: "datanode.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649" }
  - { regexp: "^nodemanager.sink.ganglia.servers=*", line: "nodemanager.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649" }
  - { regexp: "^maptask.sink.ganglia.servers=*", line: "maptask.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649" }
  - { regexp: "^reducetask.sink.ganglia.servers=*", line: "reducetask.sink.ganglia.servers={{ hostvars[groups['master'][0]].ansible_hostname }}:8649" }


_firewall_ports:
  - "80"

