---
- name: Stop the ZKFC
  become_user: "{{ _hadoop.user }}"
  shell: |
    nohup hadoop-daemon.sh stop zkfc
  register: stop_master_zkfs
  ignore_errors: true
  args:
    executable: /bin/bash
    chdir: "{{ _hadoop.base_path }}"
  environment:
    PATH: "{{ hadoop_root_dir }}/sbin:/usr/local/bin:{{ ansible_env.PATH }}"
  when: inventory_hostname in groups['master']


- name: Stop the All Hadoop Services
  become_user: "{{ _hadoop.user }}"
  shell: |
    nohup stop-all.sh
  register: stop_all_hdfs_service
  ignore_errors: true
  args:
    executable: /bin/bash
    chdir: "{{ _hadoop.base_path }}"
  environment:
    PATH: "{{ hadoop_root_dir }}/sbin:/usr/local/bin:{{ ansible_env.PATH }}"
  when: inventory_hostname in groups['master']


- name: Stop and Disable Zookeeper
  systemd:
    name: zookeeper
    state: stopped
    enabled: no
  register: stop_zookeeper
  ignore_errors: true
  when: inventory_hostname not in groups['database']

