---
- name: Stop All Hadoop Service
  become_user: "{{ _hadoop.user }}"
  shell: |
    {{ hadoop_root_dir }}/sbin/stop-all.sh
  register: stop_all_hadoop_service
  args:
    executable: /bin/bash
    chdir: "{{ _hadoop.base_path }}"
  environment:
    PATH: "{{ hadoop_root_dir }}/sbin:/usr/local/bin:{{ ansible_env.PATH }}"
  when: inventory_hostname in groups['master']


- name: Stop and Disable Zookeeper
  systemd:
    name: zookeeper
    state: stopped
    enabled: no
  when: inventory_hostname not in groups['database']

