---
# For now fail if it's not a Red Hat based system
- name: Check OS ( Spark )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags:
    - install
    - uninstall


- name: Disable Firewall
  import_tasks: disable-firewall.yml
  tags: install
  when: spark.firewall == true


- name: Install Spark
  import_tasks: install-spark.yml
  tags: install


- name: Config Spark
  import_tasks: config-spark.yml
  tags: install


- name: Uninstall Spark
  import_tasks: uninstall.yml
  tags: uninstall


- name: Enable Firewall
  import_tasks: enable-firewall.yml
  tags: uninstall
  when: spark.firewall == true


