---
- name: Check OS ( Spark )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: install, uninstall, setup, remove, config, create, delete, start, stop
  when: inventory_hostname not in groups['database']


- name: Setup Spark
  import_tasks: setup-spark.yml
  tags: setup, install
  when: (( bin is defined and bin == true ) or ( spark_all is defined and spark_all == true )) and inventory_hostname not in groups['database']


- name: Config Spark
  import_tasks: config-spark.yml
  tags: config, install
  when: (( spark is defined and spark == true ) or ( spark_all is defined and spark_all == true )) and inventory_hostname not in groups['database']


- name: Start Spark
  import_tasks: start-spark.yml
  tags: start, install
  when: (( service is defined and service == true ) or ( spark_all is defined and spark_all == true )) and inventory_hostname in groups['master']


- name: Stop Spark
  import_tasks: stop-spark.yml
  tags: stop, uninstall
  when: (( service is defined and service == true ) or ( spark_all is defined and spark_all == true )) and inventory_hostname in groups['master']


- name: Uninstall Spark
  import_tasks: uninstall-spark.yml
  tags: delete, remove, uninstall
  when: (( bin is defined and bin == true ) or ( spark_all is defined and spark_all == true )) and inventory_hostname not in groups['database']

