---
- name: Get Network Interface Name from Prefix of IP Addresses
  set_fact:
    netdev0: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', _spark.net.ipaddr0 ) | map(attribute='device') | first }}"
    netdev2: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', _spark.net.ipaddr2 ) | map(attribute='device') | first }}"
    # netdev1: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', spark.net.ipaddr1 ) | map(attribute='device') | first }}"


- name: Get IP Address from Network Device Name
  set_fact:
    ipaddr0: "{{ hostvars[inventory_hostname]['ansible_'~netdev0].ipv4.address }}"
    ipaddr2: "{{ hostvars[inventory_hostname]['ansible_'~netdev2].ipv4.address }}"
    # ipaddr1: "{{ hostvars[inventory_hostname]['ansible_'~netdev1].ipv4.address }}"


- name: Define Fact for Spark Version
  set_fact:
    spark_file_name: "spark-{{ _spark.major_version }}.{{ _spark.minor_version }}.{{ _spark.patch_version }}-bin-hadoop{{ _hadoop.major_version }}"
    spark_root_dir: "{{ _spark.base_path }}/spark-{{ _spark.major_version }}.{{ _spark.minor_version }}.{{ _spark.patch_version }}-bin-hadoop{{ _hadoop.major_version }}"
    hadoop_version: "{{ _hadoop.major_version }}.{{ _hadoop.minor_version }}.{{ _hadoop.patch_version }}"
    spark_version: "{{ _spark.major_version }}.{{ _spark.minor_version }}.{{ _spark.patch_version }}"


- name: Set Default Network Device and Address
  set_fact:
    netdev: "{{ netdev2 }}"
    _netdev: "ansible_{{ netdev2 }}"
    _ipaddr: "{{ ipaddr2 }}"


- name: Set Spark Local IP
  set_fact:
    _spark_local_ip: "{{ ipaddr2 }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"
  when: inventory_hostname in groups['master']

