---
# https://www.youngju.dev/blog/archives/hbase_fully_distributed_mode_install
# https://developer-woong.tistory.com/54
# https://www.guru99.com/hbase-installation-guide.html
# https://github.com/analytically/hadoop-ansible/tree/master/roles


- name: Create Link to Hbase Directory
  file:
    src: "{{ hbase_root_dir }}"
    dest: "{{ hbase.base_path }}/hbase"
    state: link


- name: Config Hbase Env
  template: src=hbase-env.sh.j2 dest={{ hbase_root_dir }}/conf/hbase-env.sh mode="u=rwx,g=rx,o=rx"


- name: Config Hbase hbase-site.xml
  template: src=hbase-site.xml.j2 dest="{{ hbase_root_dir }}/conf/hbase-site.xml" mode=0644 owner={{ hbase.user }} group={{ hbase.group }}


- name: Config Hbase Regionservers
  template: src={{ item }}.j2 dest={{ hbase_root_dir }}/conf/{{ item }} mode=0644 owner={{ hbase.user }} group={{ hbase.group }}
  with_items:
    - "backup-masters"
    - "regionservers"


- name: Start Hbasse Cluster
  shell: su - {{ hbase.user }} -c "{{ hbase_root_dir }}/bin/start-hbase.sh"
  when: inventory_hostname in groups['master']


- name: Print the URL of HBase Web UI
  debug:
    msg: "HBase Web UI with http://{{ hostvars[groups['master'][0]]['ansible_'~ netdev0]['ipv4']['address'] }}:60010\n
    Spark Web UI with http://{{ hostvars[groups['master'][0]]['ansible_'~ netdev0]['ipv4']['address'] }}:4040\n
    Hadoop Namenode Web UI with http://{{ hostvars[groups['master'][0]]['ansible_'~ netdev0]['ipv4']['address'] }}:50070\n
    YARN Resource Manager Web UI with http://{{ hostvars[groups['master'][0]]['ansible_'~ netdev0]['ipv4']['address'] }}:8088\n
    MapReduce JobHistory Server Web UI with http://{{ hostvars[groups['master'][0]]['ansible_'~ netdev0]['ipv4']['address'] }}:19888"
  when: inventory_hostname in groups['master']
