---
# https://www.youngju.dev/blog/archives/hbase_fully_distributed_mode_install
# https://developer-woong.tistory.com/54
# https://www.guru99.com/hbase-installation-guide.html
# https://github.com/analytically/hadoop-ansible/tree/master/roles


- name: Create Link to Hbase Directory
  file:
    src: "{{ hbase_root_dir }}"
    dest: "{{ _hbase.base_path }}/hbase"
    owner: "{{ _hadoop.user }}"
    group: "{{ _hadoop.group }}"
    state: link


- name: Config Hbase Env
  template: src=hbase-env.sh.j2 dest={{ hbase_root_dir }}/conf/hbase-env.sh mode="u=rwx,g=rx,o=rx"


- name: Config Hbase hbase-site.xml
  template: src=hbase-site.xml.j2 dest="{{ hbase_root_dir }}/conf/hbase-site.xml" mode=0644 owner={{ _hbase.user }} group={{ _hbase.group }}


- name: Config Hbase Regionservers
  template: src={{ item }}.j2 dest={{ hbase_root_dir }}/conf/{{ item }} mode=0644 owner={{ _hbase.user }} group={{ _hbase.group }}
  with_items:
    - "backup-masters"
    - "regionservers"


- name: Start Hbasse Cluster
  become_user: "{{ _hbase.user }}"
  shell: |
    nohup {{ hbase_root_dir }}/bin/start-hbase.sh
  register: start_hbase_cluster
  args:
    executable: /bin/bash
    chdir: "{{ _hbase.base_path }}"
  environment:
    PATH: "{{ hbase_root_dir }}/bin:{{ hadoop_root_dir }}/bin:/usr/local/bin:{{ ansible_env.PATH }}"
  when: inventory_hostname in groups['master']


- name: Print the URL of HBase Web UI
  debug:
    msg: "HBase Web UI with http://{{ hostvars[groups['master'][0]][_netdev]['ipv4']['address'] }}:60010"
  when: inventory_hostname in groups['master']
  # 8480 Journal Node

