---
- name: Init HDFS Path
  shell: su {{ hadoop.user }} -c "hadoop fs -mkdir -p {{ item }}"
  with_items:
    - "{{ hdfs_path }}"


- name: Change Authority
  shell: su {{ hadoop.user }} -c "hadoop fs -chmod -R 777 {{ item }}"
  with_items:
    - "{{ hdfs_path }}"


- name: Init Hive
  shell: su {{ hadoop.user }} -c "schematool -initSchema -dbType {{ db.type }}"
  async: 300
  poll: 5

