---
# https://www.youngju.dev/blog/archives/hbase_fully_distributed_mode_install
# https://developer-woong.tistory.com/54
# https://www.guru99.com/hbase-installation-guide.html
# https://github.com/analytically/hadoop-ansible/tree/master/roles


- name: Check if Apache Hbase Tarball File Already Exists
  stat: path={{ _hbase.base_path }}/{{ hbase_file_name }}.{{ _hbase.bin_type }}
  register: check_hbase_tarball


- name: Check if Apache Hbase Installation Directory Already Exists
  stat: path={{ _hbase.base_path }}/{{ hbase_file_name }}
  register: check_hbase_install_dir


- name: Sanity Check for Existence of {{ hbase_file_name }}.{{ _hbase.bin_type }} File or {{ hbase_file_name }} Directory
  debug: msg="Both {{ hbase_file_name }}.{{ _hbase.bin_type }} File and {{ hbase_file_name }} Directory Already Exists"
  changed_when: check_hbase_tarball.stat.exists == True and check_hbase_install_dir.stat.exists == True


- name: Download Hbase Software Binaries
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  with_items:
    - { url: "{{ _hbase.download_url }}/{{ hbase_version }}/hbase-{{ hbase_version }}-bin.tar.gz",
        dest: "{{ _hbase.base_path }}/hbase-{{ hbase_version }}-bin.tar.gz" }
  when: _hbase.download == true and check_hbase_tarball.stat.exists != True


- name: Copy Apache Hbase Tarball from Local Directory, roles/hbase/files
  copy: src={{ hbase_file_name }}.{{ _hbase.bin_type }} dest={{ _hbase.base_path }}/{{ hbase_file_name }}.{{ _hbase.bin_type }} mode=0644 owner={{ _hbase.user }} group={{ _hbase.group }}
  register: local_copy_dss
  when: _hbase.download == false and check_hbase_tarball.stat.exists != True


- name: Unarchive Apache Hbase Tarball
  unarchive:
    src: "{{ _hbase.base_path }}/{{ hbase_file_name }}.{{ _hbase.bin_type }}"
    dest: "{{ _hbase.base_path }}/"
    owner: "{{ _hbase.user }}"
    group: "{{ _hbase.group }}"
    mode: "0755"
    remote_src: yes
  register: unarchive_hbase_tarball
  when: check_hbase_install_dir.stat.exists == false


- name: Change Permission of Apache Hbase Directory
  file:
    path: "{{ item.dir }}"
    state: "{{ item.state }}"
    mode: "{{ item.perm }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    recurse: "{{ item.recurse }}"
  with_items:
    - { state: "directory", perm: "0755", recurse: "yes", dir: "{{ hbase_root_dir }}", owner: "{{ _hbase.user }}", group: "{{ _hbase.group }}" }

