---
- name: Check OS ( Hbase )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: install, uninstall, enable, disable, config, init, uninit, setup, remove


- name: Disable Firewall
  import_tasks: disable-firewall.yml
  tags: disable, install
  when: ( firewall is defined and firewall == true ) or ( hbase_all is defined and hbase_all == true )


- name: Install Hbase
  import_tasks: install-hbase.yml
  tags: setup, install
  when: ( hbase is defined and hbase == true ) or ( hbase_all is defined and hbase_all == true )


- name: Config Hbase
  import_tasks: config-hbase.yml
  tags: config, install
  when: ( hbase is defined and hbase == true ) or ( hbase_all is defined and hbase_all == true )


- name: Uninstall Hbase
  import_tasks: uninstall.yml
  tags: remove, delete, uninstall
  when: ( hbase is defined and hbase == true ) or ( hbase_all is defined and hbase_all == true )


- name: Enable Firewall
  import_tasks: enable-firewall.yml
  tags: enable, uninstall
  when: ( firewall is defined and firewall == true ) or ( hbase_all is defined and hbase_all == true )

