---
# https://github.com/mcsrainbow/ansible-playbook-cdh5/blob/master/roles/cdh5-hive/tasks/main.yml
- name: Check OS ( Hbase )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: install, uninstall, enable, disable, config


- name: Disable Firewall
  import_tasks: disable-firewall.yml
  tags: install
  when: hbase.firewall == true


- name: Install Hbase
  import_tasks: install-hbase.yml
  tags: install
  when: install_hbase is defined and install_hbase


- name: Config Hbase
  import_tasks: config-hbase.yml
  tags: install
  when: config_hbase is defined and config_hbase


#- name: Initialize Hbase
#  import_tasks: init-hbase.yml
#  tags: install
#  when: init_hbase is defined and init_hbase


- name: Uninstall Hbase
  import_tasks: uninstall.yml
  tags: uninstall


- name: Enable Firewall
  import_tasks: enable-firewall.yml
  tags: uninstall
  when: hbase.firewall == true

