---
- name: Stop Hbasse Cluster
  become_user: "{{ _hbase.user }}"
  shell: |
    nohup {{ hbase_root_dir }}/bin/stop-hbase.sh
  register: stop_hbase_cluster
  args:
    executable: /bin/bash
    chdir: "{{ _hbase.base_path }}"
  environment:
    PATH: "{{ hadoop_root_dir }}/bin:{{ hbase_root_dir }}/bin:/usr/local/bin:{{ ansible_env.PATH }}"
  when: inventory_hostname in groups['master']


- name: Remove Hbase Configuration, Environment and Binary
  file:
    path: "{{ item }}"
    owner: "{{ _hbase.user }}"
    group: "{{ _hbase.group }}"
    state: absent
  with_items:
    - "{{ hbase_root_dir }}/conf/hbase-site.xml"
    - "{{ _hbase.base_path }}/{{ hbase_file_name }}.{{ _hbase.bin_type }}"
    - "/etc/profile.d/hbase_env.sh"
    - "{{ hbase_root_dir }}/conf/hbase-env.sh"
    - "{{ hbase_root_dir }}/conf/backup-masters"
    - "{{ hbase_root_dir }}/conf/regionservers"
    - "{{ _hbase.base_path }}/hbase"
    - "{{ _hbase.base_path }}/{{ hbase_file_name }}"

