---
# Initialize Linux Hosts

# For now fail if it's not suppoted OS
- name: Check OS
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Set facts for network and packages informations for Linux Distribution
  import_tasks: set-facts.yml
  tags:
    - init
    - uninit

#
- name: Initialize Hosts for Red Hat / CentOS / Rocky / Ubuntu / Debian
  import_tasks: init-hosts.yml
  tags: init

#
- name: Install for Red Hat / CentOS / Rocky / Ubuntu / Debian
  import_tasks: install.yml
  tags: init

#
- name: Install for Red Hat / CentOS / Rocky / Ubuntu / Debian
  import_tasks: ssh_hadoop_user.yml
  tags: init

#
- name: Install for Red Hat / CentOS / Rocky / Ubuntu / Debian
  import_tasks: ssh_root_user.yml
  tags: init

#
- name: Uninstall for Red Hat / CentOS / Rocky / Ubuntu / Debian
  import_tasks: uninstall.yml
  tags: uninit

