---
- name: Download Hadoop Tar File If Not Downloaded
  copy: src={{ download_path }}/hadoop-{{hadoop_version}}.tar.gz dest=/tmp owner={{ user }} mode=755
  when: download_hadoop == true


- name: Copy Hadoop
  copy: src=hadoop-{{hadoop_version}}.tar.gz dest=/tmp owner={{ user }} mode=755
  when: download_hadoop == false


- name: Unzip Hadoop
  shell: "tar zxf /tmp/hadoop-{{hadoop_version}}.tar.gz -C {{ hadoop_path }}"


- name: Unzip Hadoop
  shell: "chown -R {{ user }}.{{ group }} {{ hadoop_path }}"

