---
- name: Check OS ( Ganglia )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: install, uninstall, enable, disable, config, create, delete, setup, remove


- name: Install Common Prerequisties Packages
  import_tasks: install-deps-pkgs.yml
  tags: setup, install
  when: ( pkgs is defined and pkgs == true ) or ( ganglia_all is defined and ganglia_all == true )


- name: Install Ganglia Monitor
  import_tasks: install-monitor.yml
  tags: setup, install
  when: (( monitor is defined and monitor == true ) or ( ganglia_all is defined and ganglia_all == true )) and inventory_hostname not in groups['database']


- name: Install Ganglia Mmetad
  import_tasks: install-gmetad.yml
  tags: setup, install
  when: (( gmetad is defined and gmetad == true ) or ( ganglia_all is defined and ganglia_all == true )) and inventory_hostname in groups['database']


- name: Install Ganglia Web
  import_tasks: install-web.yml
  tags: setup, install
  when: (( web is defined and web == true ) or ( ganglia_all is defined and ganglia_all == true )) and inventory_hostname in groups['database']


- name: Configure Hadoop Metrics
  import_tasks: config-hadoop-metrics.yml
  tags: config, install
  when: (( metrics is defined and metrics == true ) or ( ganglia_all is defined and ganglia_all == true )) and inventory_hostname not in groups['database']


- name: Disable Firewall
  import_tasks: ext/disable-firewall.yml
  tags: disable, install
  when: (( firewall is defined and firewall == true ) or ( ganglia_all is defined and ganglia_all == true )) and inventory_hostname in groups['database']


- name: Uninstall Ganglia Web
  import_tasks: uninstall-web.yml
  tags: delete, remove, uninstall
  when: (( web is defined and web == true ) or ( ganglia_all is defined and ganglia_all == true )) and inventory_hostname in groups['database']


- name: Uninstall Ganglia GMond
  import_tasks: uninstall-gmond.yml
  tags: delete, remove, uninstall
  when: (( gmond is defined and gmond == true ) or ( ganglia_all is defined and ganglia_all == true )) and inventory_hostname not in groups['database']


- name: Uninstall Hadoop Metrics
  import_tasks: uninstall-hadoop-metrics.yml
  tags: remove, delete, uninstall
  when: (( metrics is defined and metrics == true ) or ( ganglia_all is defined and ganglia_all == true )) and inventory_hostname not in groups['database']


- name: Uninstall Common Prerequisties Packages
  import_tasks: uninstall-deps-pkgs.yml
  tags: remove, delete, uninstall
  when: ( pkgs is defined and pkgs == true ) or ( ganglia_all is defined and ganglia_all == true )


- name: Enable Firewall
  import_tasks: ext/enable-firewall.yml
  tags: enable, uninstall
  when: (( firewall is defined and firewall == true ) or ( ganglia_all is defined and ganglia_all == true )) and inventory_hostname in groups['database']


- name: Install Common Prerequisties Packages
  package:
    name: selinux-policy-targeted
    state: present
  register: install_common_deps_pkgs


- name: Enable SELinux ( Enabling SELinux got Network(eth2) Failed )
  import_tasks: ext/enable-selinux.yml
  tags: enable, install
  when: ( selinux is defined and selinux == true ) and inventory_hostname in groups['database']


- name: Disable SELinux
  import_tasks: ext/disable-selinux.yml
  tags: disable, uninstall
  when: ( selinux is defined and selinux == true ) and inventory_hostname in groups['database']


- name: Start Hadoop
  import_tasks: ext/start-hadoop.yml
  tags: start
  when: ( hdfs is defined and hdfs == true ) and inventory_hostname not in groups['database']


- name: Stop Hadoop
  import_tasks: ext/stop-hadoop.yml
  tags: stop
  when: ( hdfs is defined and hdfs == true ) and inventory_hostname not in groups['database']

