#
- name: Verify the State of Postgres instance
  become_user: postgres
  shell: ( source {{ pgsql.base_dir }}/.bash_profile ; {{ common.pgsql_bin_dir }}/pg_ctl -V )
  register: single_postgres_state_verified
  args:
    chdir: "{{ pgsql.base_dir }}"
    executable: /bin/bash


- debug: msg={{ single_postgres_state_verified }}
  become_user: postgres
  tags: print_debug

