---
# for now fail if it's not a Red Hat based system
- name: Check OS
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or  ansible_os_family != 'Rocky'


- name: Set Facts for Package Name and List and Network Device/Address Range
  import_tasks: set-facts.yml
  tags:
    - install
    - uninstall
  when: inventory_hostname in groups['database']


- name: Enable Firewalld
  import_tasks: enable-firewall.yml
  tags: install
  when: inventory_hostname in groups['database']


- name: Install Common Prerequisties and Postgres RPM Packages For Single Instance
  import_tasks: install-pkgs.yml
  tags: install
  when: inventory_hostname in groups['database']


- name: Initialize Postgres Instance
  import_tasks: initialize-postgres.yml
  tags: install
  when: inventory_hostname in groups['database']


- name: Enable SSL for Single Postgres
  import_tasks: enable-ssl.yml
  tags: install
  when: ssl.enable == true and inventory_hostname in groups['database']


- name: Add User into PstgreSQL
  import_tasks: add-users.yml
  tags: install
  when: inventory_hostname in groups['database']


- name: Check the Status of Single PostgreSQL
  import_tasks: check-status.yml
  tags: install
  when: inventory_hostname in groups['database']


- name: Uninstall RPM Packages for PostgreSQL
  import_tasks: uninstall.yml
  tags: uninstall
  when: inventory_hostname in groups['database']


- name: Upgrade RPM Packages for PostgreSQL
  import_tasks: upgrade.yml
  tags: upgrade
  when: inventory_hostname in groups['database']

