---
# file: roles/ganglia_monitor/tasks/main.yml

- name: install Ganglia Monitor and required packages via apt
  apt: name={{ item }}
  with_items:
    - sysstat
    - php5-cli
    - ganglia-monitor
    - hddtemp
  tags: ganglia

- name: configure gmond.conf in /etc/ganglia/gmond.conf
  template: src=gmond.conf dest=/etc/ganglia/gmond.conf owner=root group=root mode=0644
  tags: ganglia
  notify:
    - restart ganglia-monitor

- name: install the device-metrics script at /usr/local/sbin
  template: src=device-metrics.php dest=/usr/local/sbin/device-metrics.php owner=root group=root mode=0644
  tags: ganglia

- name: install the device-metrics crontab at /etc/cron.d/device-metrics
  template: src=device-metrics.cron.d dest=/etc/cron.d/device-metrics owner=root group=root mode=644
  tags: ganglia